"""IEC-C1 end to end on a synthetic ggen_igniter-shaped repository, plus mutations.

The fixture repository is built with the real `git` binary in the exact pack
layout ggen_igniter uses (`priv/ggen/<pack>/{ontology.ttl, gates/NNN_x.rq,
templates/*.eex}`), with committed outputs that are faithful renders. The kernel
is recomputed with real rdflib SPARQL. Nothing is mocked.

Each mutation changes exactly one relation and must turn a court red:

* template drift   -- a committed output's mandatory prose no longer matches its
                      declared template (reflexion counterexample);
* row drift        -- one table row no longer carries its kernel value
                      (row court counterexample, not a silent flat fallback);
* identity drift   -- the frozen tree no longer contains the regenerated bytes
                      (checked by editing the kernel so regeneration differs).
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest

from autofde_lab.iec.crowns.antiunify import template_text
from autofde_lab.iec.crowns.census import census
from autofde_lab.iec.crowns.corpus import observe_checkout
from autofde_lab.iec.crowns.crown import run_c1
from autofde_lab.iec.crowns.decompile import flat_program, leave_one_out, row_program
from autofde_lab.iec.crowns.generators import declared_outputs, declared_targets
from autofde_lab.iec.crowns.kernel import pack_kernel
from autofde_lab.iec.crowns.model import IECRefusal

REPOSITORY = "example/packs"
REMOTE = f"https://github.com/{REPOSITORY}.git"

INDEX_ONTOLOGY = """@prefix ix: <https://example.invalid/index#> .
ix:a a ix:Entry ; ix:number "0001" ; ix:filename "0001-alpha-choice.md" ; ix:title "Alpha as the default" .
ix:b a ix:Entry ; ix:number "0002" ; ix:filename "0002-beta-optional.md" ; ix:title "Beta remains optional" .
ix:c a ix:Entry ; ix:number "0003" ; ix:filename "0003-gamma-boundary.md" ; ix:title "Gamma owns the boundary" .
"""
INDEX_GATE = """PREFIX ix: <https://example.invalid/index#>
SELECT ?number ?filename ?title WHERE { ?e a ix:Entry ; ix:number ?number ; ix:filename ?filename ; ix:title ?title . }
"""
INDEX_TEMPLATE = """---
to: "docs/INDEX.md"
mode: file
---
# Decisions

Generated from the index pack; never hand-edit.

| No | Title |
|---|---|
<%= for row <- Enum.sort_by(entries, & &1["number"]) do %>| [<%= row["number"] %>](<%= row["filename"] %>) | <%= row["title"] %> |
<% end %>
End of index.
"""
INDEX_OUTPUT = """# Decisions

Generated from the index pack; never hand-edit.

| No | Title |
|---|---|
| [0001](0001-alpha-choice.md) | Alpha as the default |
| [0002](0002-beta-optional.md) | Beta remains optional |
| [0003](0003-gamma-boundary.md) | Gamma owns the boundary |

End of index.
"""


def module_pack(name: str, module: str, target: str) -> dict[str, str]:
    base = f"priv/ggen/{name}"
    ontology = f"""@prefix m: <https://example.invalid/mod#> .
m:x a m:Module ; m:moduleName "{module}" .
"""
    gate = """PREFIX m: <https://example.invalid/mod#>
SELECT ?moduleName WHERE { ?x a m:Module ; m:moduleName ?moduleName . }
"""
    header = (
        f"# GENERATED by demo from {base}/ontology.ttl.\n"
        "# Do not edit. Regenerate with:\n"
        f"#   mix demo.sync --pack {name} \\\n"
        f"#     --out {target}\n"
    )
    template = (
        f'---\nto: "{target}"\nmode: file\n---\n'
        '<%\n  [row | _] = module\n  module_name = row["moduleName"]\n%>'
        + header
        + "defmodule <%= module_name %> do\n  def hello, do: :world\nend\n"
    )
    output = header + f"defmodule {module} do\n  def hello, do: :world\nend\n"
    return {
        f"{base}/ontology.ttl": ontology,
        f"{base}/gates/010_module.rq": gate,
        f"{base}/templates/mod.ex.eex": template,
        target: output,
    }


def fixture_files() -> dict[str, str]:
    files = {
        "priv/ggen/index-pack/ontology.ttl": INDEX_ONTOLOGY,
        "priv/ggen/index-pack/gates/010_entries.rq": INDEX_GATE,
        "priv/ggen/index-pack/templates/readme.md.eex": INDEX_TEMPLATE,
        "docs/INDEX.md": INDEX_OUTPUT,
        "docs/0001-alpha-choice.md": "# 1\n",
        "docs/0002-beta-optional.md": "# 2\n",
        "docs/0003-gamma-boundary.md": "# 3\n",
        "docs/0004-delta-unindexed.md": "# 4\n",
    }
    files.update(module_pack("alpha-pack", "Demo.Alpha", "lib/demo/alpha.ex"))
    files.update(module_pack("beta-pack", "Demo.Beta", "lib/demo/beta.ex"))
    files.update(module_pack("gamma-pack", "Demo.Gamma", "lib/demo/gamma.ex"))
    return files


def git(repo: Path, *args: str) -> str:
    return subprocess.run(
        ["git", "-C", str(repo), *args], capture_output=True, check=True
    ).stdout.decode()


def make_repo(root: Path, files: dict[str, str]) -> Path:
    root.mkdir(parents=True)
    git(root, "init", "-q", "-b", "main")
    git(root, "config", "user.email", "iec@example.invalid")
    git(root, "config", "user.name", "IEC test")
    git(root, "remote", "add", "origin", REMOTE)
    for path, text in files.items():
        (root / path).parent.mkdir(parents=True, exist_ok=True)
        (root / path).write_text(text, encoding="utf-8")
    git(root, "add", "-A")
    git(root, "commit", "-q", "-m", "fixture")
    return root


def run(tmp_path: Path, files: dict[str, str]) -> dict:
    repo = make_repo(tmp_path / "repo", files)
    return run_c1(
        repo, tmp_path / "out", tmp_path / "regenerated", repository=REPOSITORY
    )


def courts(receipt: dict, target: str) -> dict[str, str]:
    subject = next(s for s in receipt["subjects"] if s["target"] == target)
    return {name: court["verdict"] for name, court in subject["courts"].items()}


def test_faithful_outputs_are_regenerated_and_validated(tmp_path):
    receipt = run(tmp_path, fixture_files())
    assert receipt["tree_identity"] == "PASS"
    assert receipt["header_family"] == "PASS"
    assert courts(receipt, "docs/INDEX.md") == {
        "iec-c1-static-row/1": "PASS",
        "ggen_igniter-native/1": "BLOCKED",
    }
    for target in ("lib/demo/alpha.ex", "lib/demo/beta.ex", "lib/demo/gamma.ex"):
        assert courts(receipt, target)["iec-c1-static-flat/1"] == "PASS"
    assert len(receipt["validated_claims"]) == 4
    # regenerated bytes landed in the isolated destination, identical to the commit
    regenerated = (tmp_path / "regenerated" / "docs/INDEX.md").read_text(
        encoding="utf-8"
    )
    assert regenerated == INDEX_OUTPUT
    plan = json.loads((tmp_path / "out" / "promotion-plan.json").read_text())
    uncovered = [
        item
        for candidate in plan["candidates"]
        if candidate["id"] == "PROMO-C1-03"
        for item in candidate["evidence"]
    ]
    assert uncovered and uncovered[0]["uncovered_matches"] == [
        "0004-delta-unindexed.md"
    ]


def test_replay_is_byte_identical(tmp_path):
    files = fixture_files()
    repo = make_repo(tmp_path / "repo", files)
    first = run_c1(repo, tmp_path / "a", tmp_path / "ra", repository=REPOSITORY)
    second = run_c1(repo, tmp_path / "b", tmp_path / "rb", repository=REPOSITORY)
    assert first["run_id"] == second["run_id"]
    for path in (tmp_path / "a").rglob("*"):
        if path.is_file():
            assert (
                path.read_bytes()
                == (tmp_path / "b" / path.relative_to(tmp_path / "a")).read_bytes()
            )


def test_mutation_template_drift_is_a_reflexion_counterexample(tmp_path):
    files = fixture_files()
    files["docs/INDEX.md"] = INDEX_OUTPUT.replace(
        "never hand-edit", "hand-edited anyway"
    )
    receipt = run(tmp_path, files)
    verdicts = courts(receipt, "docs/INDEX.md")
    assert verdicts["iec-c1-static-row/1"] == "COUNTEREXAMPLE"
    subject = next(s for s in receipt["subjects"] if s["target"] == "docs/INDEX.md")
    failing = {c["verifier"] for c in subject["counterexamples"]}
    # the bytes still regenerate -- the drift is from the declared template
    assert failing == {"declared-template-mandatory-literals"}
    lines = (tmp_path / "out" / "counterexamples.jsonl").read_text().splitlines()
    assert any(json.loads(line)["subject"].endswith(":docs/INDEX.md") for line in lines)


def test_mutation_row_drift_is_a_row_court_counterexample_not_a_flat_fallback(tmp_path):
    files = fixture_files()
    files["docs/INDEX.md"] = INDEX_OUTPUT.replace(
        "Beta remains optional", "Beta is now mandatory"
    )
    receipt = run(tmp_path, files)
    verdicts = courts(receipt, "docs/INDEX.md")
    assert "iec-c1-static-flat/1" not in verdicts
    assert verdicts["iec-c1-static-row/1"] == "COUNTEREXAMPLE"
    subject = next(s for s in receipt["subjects"] if s["target"] == "docs/INDEX.md")
    assert "row-template-leave-one-out" in {
        c["verifier"] for c in subject["counterexamples"]
    }
    assert any(r["stage"] == "row-regenerate" for r in subject["refusals"])


def test_mutation_header_restatement_drift_breaks_the_family_court(tmp_path):
    files = fixture_files()
    files["lib/demo/beta.ex"] = files["lib/demo/beta.ex"].replace(
        "--out lib/demo/beta.ex", "--out lib/demo/old.ex"
    )
    receipt = run(tmp_path, files)
    assert receipt["header_family"] == "COUNTEREXAMPLE"


def test_row_program_units(tmp_path):
    rows = [
        {
            "number": "0002",
            "filename": "0002-b.md",
            "title": "Ay",
            "status": "Accepted",
        },
        {
            "number": "0001",
            "filename": "0001-a.md",
            "title": "Mid",
            "status": "Accepted",
        },
        {
            "number": "0003",
            "filename": "0003-c.md",
            "title": "Zed",
            "status": "Accepted",
        },
    ]
    text = (
        "head\n"
        + "".join(
            f"| [{r['number']}]({r['filename']}) | {r['title']} | {r['status']} |\n"
            for r in sorted(rows, key=lambda r: r["number"])
        )
        + "tail\n"
    )
    program = row_program(text, "adrs", rows)
    assert (
        template_text(program.row_template)
        == "| [{{X0}}]({{X1}}) | {{X2}} | Accepted |\n"
    )
    assert program.hole_variables == {0: ["number"], 1: ["filename"], 2: ["title"]}
    # titles do not sort in number order, so only number and filename survive
    assert set(program.order_hypotheses) == {"number", "filename"}
    assert program.constant_literals == ({"variable": "status", "value": "Accepted"},)
    assert program.regenerate(rows) == text
    assert all(
        result["verdict"] == "PASS" for result in leave_one_out(text, "adrs", rows)
    )
    with pytest.raises(IECRefusal):
        row_program("no rows here\n", "adrs", rows)


def test_flat_program_refuses_ambiguous_regeneration():
    program = flat_program(
        "x = shared; y = shared\n", {"k:a": "shared", "k:b": "shared"}
    )
    assert program.coverage()["ambiguous_holes"] == 2
    assert (
        program.regenerate({"k:a": "shared", "k:b": "shared"})
        == "x = shared; y = shared\n"
    )
    with pytest.raises(IECRefusal) as refused:
        program.regenerate({"k:a": "one", "k:b": "two"})
    assert refused.value.code == "UNKNOWN_EQUIVALENCE"


def test_declared_outputs_cover_eex_and_ggen_toml_and_flag_contests(tmp_path):
    files = fixture_files()
    files["ggen.toml"] = (
        '[generation]\noutput_dir = "."\n\n[[generation.rules]]\nname = "idx"\n'
        'query = { file = "q.rq" }\ntemplate = { file = "t.tera" }\n'
        'output_file = "docs/INDEX.md"\nmode = "Overwrite"\n'
    )
    repo = make_repo(tmp_path / "repo", files)
    frozen = observe_checkout(
        repo,
        repository=REPOSITORY,
        branch="main",
        visibility="public",
        inclusion_reason="t",
    )
    base = census(frozen, repo)
    outputs = declared_outputs(base, repo)
    assert {(o.syntax, o.target) for o in outputs} >= {
        ("eex-frontmatter", "docs/INDEX.md"),
        ("ggen-toml-rule", "docs/INDEX.md"),
        ("eex-frontmatter", "lib/demo/alpha.ex"),
    }
    targets = declared_targets(outputs)
    assert targets["docs/INDEX.md"]["contested"] == "true"
    kernel = pack_kernel(base, repo, "priv/ggen/index-pack/templates/readme.md.eex")
    assert kernel.engine["name"] == "rdflib"
    # kernel rows are in canonical (content-id) order, not domain order
    assert sorted(row["number"] for row in kernel.rows["entries"]) == [
        "0001",
        "0002",
        "0003",
    ]
    assert kernel.declaration["template.to"] == "docs/INDEX.md"
