"""Unit/integration checkpoints for IEC's first executable slice.

These tests intentionally are not named Chicago: they exercise the real IEC
Python components for deterministic local semantics, but not a real sibling
repository checkout, ggen-create process, ggen manufacture, or BRCE actuation.
"""

from __future__ import annotations

import pytest

from autofde_lab.iec.anti_unification import AntiUnifier
from autofde_lab.iec.corpus import CorpusFreezer
from autofde_lab.iec.correspondence import CorrespondenceEngine
from autofde_lab.iec.cost import CostVector, KernelCandidate, dominates
from autofde_lab.iec.disposition import (
    Disposition,
    DispositionCourt,
    PreservationFence,
)
from autofde_lab.iec.engine import InverseEcosystemCompiler
from autofde_lab.iec.equivalence import EquivalenceCourt, exact_equality_verifier
from autofde_lab.iec.ggen_create_adapter import GgenCreateAdapter
from autofde_lab.iec.hypothesis import Hypothesis, HypothesisFrontier
from autofde_lab.iec.incremental import CacheEntry, CacheKey, ObservationCache
from autofde_lab.iec.metrics import IECMetrics
from autofde_lab.iec.model import (
    ArtifactClass,
    ClaimCeiling,
    Counterexample,
    EquivalenceDimension,
    RepositorySubject,
)
from autofde_lab.iec.observations import ObservationExtractor, PassiveFile
from autofde_lab.iec.promotion import (
    CapabilityOwner,
    PromotionKind,
    PromotionRouter,
)
from autofde_lab.iec.retirement import RetirementLedger, RetirementStatus


def subject(
    name: str = "seanchatmangpt/example",
    revision: str = "a" * 40,
    visibility: str = "public",
) -> RepositorySubject:
    return RepositorySubject(
        repository=name,
        revision=revision,
        default_branch="main",
        visibility=visibility,
    )


def test_subject_identity_is_deterministic_and_revision_bound() -> None:
    left = subject()
    right = subject()
    moved = subject(revision="b" * 40)
    assert left.subject_id == right.subject_id
    assert left.subject_id != moved.subject_id


def test_corpus_freeze_refuses_private_identity_by_default() -> None:
    freezer = CorpusFreezer()
    with pytest.raises(PermissionError, match="REFUSED_PRIVATE_IDENTITY_LEAK"):
        freezer.freeze([subject(visibility="private")])


def test_corpus_freeze_refuses_duplicate_repository_subjects() -> None:
    freezer = CorpusFreezer()
    with pytest.raises(ValueError, match="duplicate repository identity"):
        freezer.freeze([subject(), subject(revision="b" * 40)])


def test_corpus_compare_names_moved_subject_as_topology_failure() -> None:
    freezer = CorpusFreezer()
    prior = freezer.freeze([subject()])
    current = freezer.freeze([subject(revision="b" * 40)])
    failures = freezer.compare(prior, current)
    assert len(failures) == 1
    assert failures[0].kind.value == "BLOCKED_CORPUS_IDENTITY"
    assert "repository moved" in failures[0].detail


def test_path_escape_is_refused() -> None:
    with pytest.raises(PermissionError, match="REFUSED_PATH_ESCAPE"):
        ObservationExtractor.normalize_path("../secret")


def test_unknown_source_is_not_mislabeled_irreducible() -> None:
    artifact_class, producer, reason = ObservationExtractor.classify(
        "src/app.py",
        b"def main():\n    return 1\n",
    )
    assert artifact_class is ArtifactClass.UNKNOWN
    assert producer is None
    assert reason


def test_known_canonical_semantic_inputs_are_canonical() -> None:
    artifact_class, _, _ = ObservationExtractor.classify(
        "ontology/domain.ttl",
        b"@prefix ex: <urn:example:> .\n",
    )
    assert artifact_class is ArtifactClass.CANONICAL_SOURCE


def test_generated_marker_without_known_producer_stays_unknown() -> None:
    artifact_class, producer, reason = ObservationExtractor.classify(
        "generated/file.py",
        b"# GENERATED BY mysterious-machine\n",
    )
    assert artifact_class is ArtifactClass.UNKNOWN
    assert producer is None
    assert "producer identity is unknown" in reason


def test_generated_ggen_projection_requires_and_records_producer() -> None:
    artifact_class, producer, reason = ObservationExtractor.classify(
        "src/generated.py",
        b"# GENERATED BY ggen - do not hand-edit\n",
    )
    assert artifact_class is ArtifactClass.GENERATED_PROJECTION
    assert producer == "ggen"
    assert reason is None


def test_anti_unification_reconstructs_every_member() -> None:
    members = [
        {"name": "alpha", "port": 1, "flags": ["x", True]},
        {"name": "beta", "port": 2, "flags": ["x", False]},
        {"name": "gamma", "port": 3, "flags": ["x", True]},
    ]
    result = AntiUnifier().generalize(
        members,
        member_ids=("a", "b", "c"),
    )
    assert [result.reconstruct(i) for i in range(3)] == members
    assert result.template["flags"][0] == "x"
    assert result.template["name"] != "alpha"


def test_anti_unification_generalizes_whole_incompatible_shape() -> None:
    members = [{"x": 1}, {"x": 1, "y": 2}]
    result = AntiUnifier().generalize(members)
    assert result.reconstruct(0) == members[0]
    assert result.reconstruct(1) == members[1]


def test_correspondence_similarity_remains_candidate() -> None:
    engine = CorrespondenceEngine(threshold=0.3)
    candidates = engine.lexical_candidates(
        [
            ("a", "authority receipt replay standing", ("ev-a",)),
            ("b", "authority receipt replay verifier", ("ev-b",)),
        ]
    )
    assert len(candidates) == 1
    candidate = candidates[0]
    assert candidate.relation.endswith("Candidate")
    assert "similarity_is_not_equivalence" in candidate.exclusions
    assert candidate.required_verifier == "iec.translation-validation"


def test_equivalence_court_preserves_counterexample() -> None:
    court = EquivalenceCourt()
    court.register(
        EquivalenceDimension.SYNTAX,
        "exact/v1",
        exact_equality_verifier,
    )
    result = court.validate(
        original_subject_id="original",
        generated_subject_id="generated",
        original={"x": 1},
        generated={"x": 2},
        dimensions=(EquivalenceDimension.SYNTAX,),
        claim_ceiling=ClaimCeiling.STRUCTURAL_EQUIVALENCE_ONLY,
    )
    assert not result.passed
    assert len(result.counterexamples) == 1
    assert result.counterexamples[0].expected == {"x": 1}
    assert result.counterexamples[0].actual == {"x": 2}


def test_equivalence_court_pass_is_dimension_and_verifier_bound() -> None:
    court = EquivalenceCourt()
    court.register(
        EquivalenceDimension.SYNTAX,
        "exact/v1",
        exact_equality_verifier,
    )
    result = court.validate(
        original_subject_id="original",
        generated_subject_id="generated",
        original={"x": 1},
        generated={"x": 1},
        dimensions=(EquivalenceDimension.SYNTAX,),
        claim_ceiling=ClaimCeiling.STRUCTURAL_EQUIVALENCE_ONLY,
    )
    assert result.passed
    assert result.dimensions == (EquivalenceDimension.SYNTAX,)
    assert result.verifier_set_id
    assert len(result.verifier_receipts) == 1


def test_equivalence_court_refuses_unregistered_dimension() -> None:
    court = EquivalenceCourt()
    court.register(
        EquivalenceDimension.SYNTAX,
        "exact/v1",
        exact_equality_verifier,
    )
    with pytest.raises(KeyError, match="UNSUPPORTED_EQUIVALENCE_DIMENSION"):
        court.validate(
            original_subject_id="original",
            generated_subject_id="generated",
            original={},
            generated={},
            dimensions=(EquivalenceDimension.RUNTIME_BEHAVIOR,),
            claim_ceiling=ClaimCeiling.BOUNDED_RUNTIME_EQUIVALENCE_ONLY,
        )


def test_retirement_requires_recurrence_replacement_and_replay() -> None:
    ledger = RetirementLedger(recurrence_threshold=2)
    first = ledger.observe("classify-generated-source", "o1")
    assert first.status is RetirementStatus.OBSERVED_ONCE
    second = ledger.observe("classify-generated-source", "o2")
    assert second.status is RetirementStatus.MECHANIZATION_CANDIDATE

    mechanized = ledger.bind_replacement(
        "classify-generated-source",
        deterministic_replacement="ObservationExtractor.classify",
        verifier_id="iec-test/v1",
    )
    assert mechanized.status is RetirementStatus.MECHANIZED

    failed = ledger.verify_replay(
        "classify-generated-source",
        replay_receipt="failed-run",
        equivalent=False,
    )
    assert failed.status is RetirementStatus.MECHANIZED

    retired = ledger.verify_replay(
        "classify-generated-source",
        replay_receipt="receipt:ok",
        equivalent=True,
    )
    assert retired.status is RetirementStatus.RETIRED_FROM_LLM


def preservation_fence() -> PreservationFence:
    return PreservationFence(
        system="example repository",
        boundary="public API",
        origin="historical implementation",
        function="manufacture example",
        consumers=("consumer-a",),
        authority="SELECT/CONSTRUCT only",
        compatibility=("api/v1",),
        historical_reason="original implementation",
        replacement_path="ggen-marketplace:example-pack",
        rollback_path="restore exact git subject",
    )


def test_destructive_disposition_requires_replacement_rollback_and_verifier() -> None:
    fence = preservation_fence()
    court = DispositionCourt()
    candidate = court.propose(
        subject_id="subject",
        disposition=Disposition.ARCHIVE,
        reason="replacement translation-validated",
        fence=fence,
        verifier_set_ids=("verifier-set",),
    )
    assert candidate.standing == "CANDIDATE"
    assert candidate.authority_required == "BRCE"

    bad_fence = PreservationFence(
        system=fence.system,
        boundary=fence.boundary,
        origin=fence.origin,
        function=fence.function,
        consumers=fence.consumers,
        authority=fence.authority,
        compatibility=fence.compatibility,
        historical_reason=fence.historical_reason,
        replacement_path=None,
        rollback_path=fence.rollback_path,
    )
    with pytest.raises(ValueError, match="replacement path required"):
        court.propose(
            subject_id="subject",
            disposition=Disposition.DELETE,
            reason="looks redundant",
            fence=bad_fence,
            verifier_set_ids=("verifier-set",),
        )


def test_kernel_dominance_requires_same_proof_obligations() -> None:
    base = dict(
        covered_observation_ids=("o1", "o2"),
        verifier_set_ids=("v1",),
        preservation_fence_ids=("f1",),
    )
    left = KernelCandidate(
        kernel_id="small",
        cost=CostVector(1, 1, 0, 0, 0),
        **base,
    )
    right = KernelCandidate(
        kernel_id="large",
        cost=CostVector(10, 2, 1, 1, 0),
        **base,
    )
    assert dominates(left, right)

    incomparable = KernelCandidate(
        kernel_id="different-proof",
        covered_observation_ids=base["covered_observation_ids"],
        verifier_set_ids=("v2",),
        preservation_fence_ids=base["preservation_fence_ids"],
        cost=CostVector(0, 0, 0, 0, 0),
    )
    assert not dominates(incomparable, right)


def test_incremental_cache_invalidates_dependents_transitively() -> None:
    cache = ObservationCache()
    root = CacheKey("s", "parser", "1", "input-a")
    child = CacheKey("s", "semantic", "1", "input-b")
    grandchild = CacheKey("s", "kernel", "1", "input-c")
    cache.put(CacheEntry(root, "out-root"))
    cache.put(CacheEntry(child, "out-child", (root.key,)))
    cache.put(CacheEntry(grandchild, "out-grandchild", (child.key,)))
    invalidated = cache.invalidate(root)
    assert invalidated == tuple(sorted((root.key, child.key, grandchild.key)))
    assert cache.identities() == ()


def test_ggen_create_adapter_constructs_intents_not_execution() -> None:
    adapter = GgenCreateAdapter(executable_revision="eaa463af")
    plan = adapter.plan_capture(
        subject(),
        generator_name="example",
        included_paths=("src/a.py", "pyproject.toml"),
    )
    assert len(plan.intents) == 4
    assert all(intent.authority == "NONE" for intent in plan.intents)
    assert all(intent.executable_revision == "eaa463af" for intent in plan.intents)


def test_promotion_router_preserves_ownership_and_zero_authority() -> None:
    candidate = PromotionRouter().route(
        kind=PromotionKind.REUSABLE_PACK,
        artifact_identity="kernel:receipt-profile",
        source_evidence_ids=("ev1",),
        verifier_receipt_ids=("vr1",),
    )
    assert candidate.owner is CapabilityOwner.GGEN_MARKETPLACE
    assert candidate.authority == "NONE"
    assert candidate.standing == "CANDIDATE"


def test_hypothesis_frontier_requires_change_after_counterexample() -> None:
    frontier = HypothesisFrontier()
    hypothesis = frontier.add(
        Hypothesis(
            covered_observation_ids=("o1",),
            excluded_observation_ids=(),
            kernel_delta={"rule": "a"},
            generator_delta={"template": "a"},
            required_residue=(),
            predicted_consequences=("same-output",),
            falsifier="translation validation mismatch",
            estimated_cost=1.0,
        )
    )
    counterexample = Counterexample(
        hypothesis_id=hypothesis.hypothesis_id,
        dimension=EquivalenceDimension.SYNTAX,
        verifier_id="exact/v1",
        expected="a",
        actual="b",
        detail="mismatch",
    )
    falsified = frontier.falsify(hypothesis.hypothesis_id, counterexample)
    with pytest.raises(ValueError, match="unchanged failed hypothesis"):
        frontier.refine(
            falsified.hypothesis_id,
            kernel_delta={"rule": "a"},
            generator_delta={"template": "a"},
            required_residue=(),
            predicted_consequences=("same-output",),
            falsifier="same falsifier",
            estimated_cost=1.0,
        )


def test_metrics_are_descriptive_and_zero_denominator_safe() -> None:
    metrics = IECMetrics(
        admitted_artifacts=10,
        classified_artifacts=8,
        recurring_transforms=4,
        mechanized_transforms=3,
        semantic_units=20,
        irreducible_units=2,
        active_hypotheses_tested=5,
        hypotheses_falsified=2,
        repeated_reasoning_classes=3,
        retired_reasoning_classes=1,
    )
    assert metrics.coverage == 0.8
    assert metrics.mechanization == 0.75
    assert metrics.residue == 0.1
    assert metrics.counterexample_yield == 0.4
    assert metrics.retirement == pytest.approx(1 / 3)


def test_engine_composes_pure_first_slice_end_to_end() -> None:
    compiler = InverseEcosystemCompiler(correspondence_threshold=0.2)
    original = subject("seanchatmangpt/original", "1" * 40)
    generated = subject("seanchatmangpt/generated", "2" * 40)
    session = compiler.freeze((original, generated))

    session = compiler.observe(
        session,
        original,
        (
            PassiveFile("ontology/domain.ttl", b"@prefix ex: <urn:x:> ."),
            PassiveFile("src/generated.py", b"# GENERATED BY ggen\n"),
        ),
    )
    assert len(session.analyses) == 1
    assert session.analyses[0].artifacts[0].artifact_class is ArtifactClass.CANONICAL_SOURCE

    session = compiler.generalize(
        session,
        ({"name": "a", "port": 1}, {"name": "b", "port": 2}),
        member_ids=("a", "b"),
    )
    assert session.generalizations[-1].reconstruct(0) == {"name": "a", "port": 1}

    court = EquivalenceCourt()
    court.register(
        EquivalenceDimension.SYNTAX,
        "exact/v1",
        exact_equality_verifier,
    )
    session = compiler.validate(
        session,
        court=court,
        original_subject_id=original.subject_id,
        generated_subject_id=generated.subject_id,
        original={"api": ["x"]},
        generated={"api": ["x"]},
        dimensions=(EquivalenceDimension.SYNTAX,),
        claim_ceiling=ClaimCeiling.STRUCTURAL_EQUIVALENCE_ONLY,
    )
    assert session.validations[-1].passed

    session = compiler.observe_reasoning(
        session,
        identity="classify-artifact",
        occurrence_id="r1",
    )
    session = compiler.observe_reasoning(
        session,
        identity="classify-artifact",
        occurrence_id="r2",
    )
    session = compiler.bind_reasoning_replacement(
        session,
        identity="classify-artifact",
        deterministic_replacement="ObservationExtractor.classify",
        verifier_id="iec-tests/v1",
    )
    session = compiler.retire_reasoning(
        session,
        identity="classify-artifact",
        replay_receipt="receipt:replay-ok",
        equivalent=True,
    )
    assert session.reasoning_classes[-1].status is RetirementStatus.RETIRED_FROM_LLM
