"""Cross-repository family, generator-gap, process, and falsifier tests."""

from __future__ import annotations

from autofde_lab.iec.engine import InverseEcosystemCompiler
from autofde_lab.iec.falsifier import Falsifier, FalsifierCourt
from autofde_lab.iec.family import family_candidates, repository_signature
from autofde_lab.iec.generator_gap import (
    GeneratorGapDetector,
    unknown_source_requirement,
)
from autofde_lab.iec.manufacture import (
    CapabilityStanding,
    GeneratorCapability,
    ManufactureRouter,
)
from autofde_lab.iec.model import ArtifactClass, ArtifactRecord, RepositorySubject
from autofde_lab.iec.observations import PassiveFile
from autofde_lab.iec.process_log import (
    IECActivity,
    IECEvent,
    IECProcessCourt,
    IECProcessLog,
)


def subject(name: str, revision: str) -> RepositorySubject:
    return RepositorySubject(
        repository=name,
        revision=revision,
        default_branch="main",
    )


def analysis(name: str, revision: str, generated_by: str = "ggen"):
    compiler = InverseEcosystemCompiler()
    repo = subject(name, revision)
    session = compiler.freeze((repo,))
    generated_marker = f"# GENERATED BY {generated_by}\n".encode()
    session = compiler.observe(
        session,
        repo,
        (
            PassiveFile("ontology/domain.ttl", b"@prefix ex: <urn:x:> ."),
            PassiveFile("src/generated.py", generated_marker),
            PassiveFile("src/unknown.py", b"def f(): return 1\n"),
        ),
    )
    return session.analyses[0]


def test_repository_family_signature_discovers_repeated_topology() -> None:
    left = repository_signature(
        analysis("seanchatmangpt/a", "a" * 40)
    )
    right = repository_signature(
        analysis("seanchatmangpt/b", "b" * 40)
    )
    candidates = family_candidates((left, right), threshold=0.8)
    assert len(candidates) == 1
    assert candidates[0].score == 1.0
    assert candidates[0].required_verifier == "iec.cross-repository-equivalence"


def test_repository_family_is_only_candidate_even_when_score_is_one() -> None:
    left = repository_signature(
        analysis("seanchatmangpt/a", "a" * 40)
    )
    right = repository_signature(
        analysis("seanchatmangpt/b", "b" * 40)
    )
    candidate = family_candidates((left, right), threshold=1.0)[0]
    assert not hasattr(candidate, "equivalent")
    assert candidate.required_verifier


def test_generator_gap_records_unsupported_instead_of_handwriting() -> None:
    artifact = ArtifactRecord(
        subject_id="subject",
        path="src/unknown.py",
        artifact_class=ArtifactClass.UNKNOWN,
        content_digest="sha256:unknown",
        unknown_reason="producer unknown",
    )
    detector = GeneratorGapDetector(
        ManufactureRouter(),
        requirement_for=unknown_source_requirement,
    )
    gaps = detector.detect((artifact,))
    assert len(gaps) == 1
    assert gaps[0].failure.kind.value == "UNSUPPORTED_GENERATOR_CAPABILITY"


def test_generator_gap_closes_when_admitted_capability_exists() -> None:
    artifact = ArtifactRecord(
        subject_id="subject",
        path="src/unknown.py",
        artifact_class=ArtifactClass.UNKNOWN,
        content_digest="sha256:unknown",
        unknown_reason="producer unknown",
    )
    router = ManufactureRouter(
        (
            GeneratorCapability(
                capability_id="example/source-generator",
                owner="seanchatmangpt/ggen-marketplace",
                input_kind="semantic-source",
                output_kind="source-projection",
                standing=CapabilityStanding.ADMITTED,
                evidence_ids=("evidence",),
            ),
        )
    )
    detector = GeneratorGapDetector(
        router,
        requirement_for=unknown_source_requirement,
    )
    assert detector.detect((artifact,)) == ()


def test_process_court_detects_validate_before_manufacture() -> None:
    log = IECProcessLog.build(
        (
            IECEvent(
                0,
                IECActivity.CORPUS_FREEZE,
                ("subject",),
                ("e0",),
            ),
            IECEvent(
                1,
                IECActivity.OBSERVE,
                ("subject",),
                ("e1",),
            ),
            IECEvent(
                2,
                IECActivity.VALIDATE,
                ("subject",),
                ("e2",),
            ),
        )
    )
    issues = IECProcessCourt().check(log)
    assert len(issues) == 1
    assert "MANUFACTURE" in issues[0].detail


def test_process_court_accepts_ordered_manufacture_validation_path() -> None:
    activities = (
        IECActivity.CORPUS_FREEZE,
        IECActivity.OBSERVE,
        IECActivity.CORRESPONDENCE,
        IECActivity.GENERALIZE,
        IECActivity.MANUFACTURE,
        IECActivity.VALIDATE,
        IECActivity.PROMOTE,
    )
    log = IECProcessLog.build(
        tuple(
            IECEvent(index, activity, ("subject",), (f"e{index}",))
            for index, activity in enumerate(activities)
        )
    )
    assert IECProcessCourt().check(log) == ()


def test_falsifier_court_distinguishes_rejection_from_non_rejection() -> None:
    subject_value = {"count": 2}
    court = FalsifierCourt()
    report = court.run(
        subject_value,
        (
            Falsifier(
                "count-at-most-one",
                "Reject if more than one consequence exists",
                lambda value: (
                    value["count"] > 1,
                    f"count={value['count']}",
                ),
            ),
            Falsifier(
                "count-nonnegative",
                "Reject negative counts",
                lambda value: (
                    value["count"] < 0,
                    f"count={value['count']}",
                ),
            ),
        ),
    )
    assert report.rejected
    results = {result.falsifier_id: result for result in report.results}
    assert results["count-at-most-one"].rejected
    assert not results["count-nonnegative"].rejected
