"""Real RDF/SPARQL/pySHACL courts for IEC semantic capital."""

from __future__ import annotations

from pathlib import Path

from rdflib import Graph

from autofde_lab.iec.model import RepositorySubject
from autofde_lab.iec.observations import ObservationExtractor, PassiveFile
from autofde_lab.iec.rdf_projection import project_repository
from autofde_lab.iec.shacl_court import validate_graph

ROOT = Path(__file__).parents[2]
ONTOLOGY = ROOT / "ontology" / "inverse-ecosystem-compiler.ttl"
SHAPES = ROOT / "ontology" / "shapes" / "inverse-ecosystem-compiler.shacl.ttl"
QUERIES = ROOT / "ontology" / "queries" / "iec"


def subject() -> RepositorySubject:
    return RepositorySubject(
        repository="seanchatmangpt/example",
        revision="a" * 40,
        default_branch="main",
    )


def load_graph(path: Path) -> Graph:
    graph = Graph()
    graph.parse(path, format="turtle")
    return graph


def test_iec_ontology_and_shapes_are_real_parseable_rdf() -> None:
    ontology = load_graph(ONTOLOGY)
    shapes = load_graph(SHAPES)
    assert len(ontology) > 20
    assert len(shapes) > 20


def test_pyshacl_accepts_valid_repository_subject_and_rejects_missing_revision() -> (
    None
):
    ontology = load_graph(ONTOLOGY)
    shapes = load_graph(SHAPES)

    valid = Graph().parse(
        data="""
@prefix iec: <urn:autofde-lab:iec:> .
@prefix ex: <urn:test:> .

ex:repo a iec:RepositorySubject ;
    iec:repository "seanchatmangpt/example" ;
    iec:revision "aaaaaaaa" ;
    iec:defaultBranch "main" ;
    iec:visibility "public" .
""",
        format="turtle",
    )
    valid_result = validate_graph(valid, shapes, ontology_graph=ontology)
    assert valid_result.conforms
    assert valid_result.claim_ceiling == "STRUCTURAL_RDF_SHACL_CONFORMANCE_ONLY"

    invalid = Graph().parse(
        data="""
@prefix iec: <urn:autofde-lab:iec:> .
@prefix ex: <urn:test:> .

ex:repo a iec:RepositorySubject ;
    iec:repository "seanchatmangpt/example" ;
    iec:defaultBranch "main" ;
    iec:visibility "public" .
""",
        format="turtle",
    )
    invalid_result = validate_graph(invalid, shapes, ontology_graph=ontology)
    assert not invalid_result.conforms
    assert invalid_result.report_graph_digest != valid_result.report_graph_digest


def test_pyshacl_refuses_replacement_disposition_without_rollback() -> None:
    ontology = load_graph(ONTOLOGY)
    shapes = load_graph(SHAPES)
    data = Graph().parse(
        data="""
@prefix iec: <urn:autofde-lab:iec:> .
@prefix ex: <urn:test:> .

ex:v a iec:EquivalenceCourt .

ex:d a iec:ReplacementDispositionCandidate ;
    iec:replacementPath "ggen-marketplace/example-pack" ;
    iec:verifierSet ex:v .
""",
        format="turtle",
    )
    result = validate_graph(data, shapes, ontology_graph=ontology)
    assert not result.conforms


def test_unknown_and_generated_queries_run_against_real_rdf_projection() -> None:
    repo = subject()
    extractor = ObservationExtractor()
    artifacts, observations = extractor.extract_repository(
        repo,
        (
            PassiveFile("src/unknown.py", b"def f(): return 1\n"),
            PassiveFile(
                "src/generated.py",
                b"# GENERATED BY ggen - do not hand-edit\n",
            ),
        ),
    )
    data = Graph()
    data.parse(
        data=project_repository(repo, artifacts, observations),
        format="nt",
    )

    unknown_query = (QUERIES / "010_unknown_artifacts.rq").read_text()
    unknown_rows = list(data.query(unknown_query))
    assert len(unknown_rows) == 1
    assert str(unknown_rows[0].path) == "src/unknown.py"

    generated_query = (QUERIES / "020_generated_artifacts.rq").read_text()
    generated_rows = list(data.query(generated_query))
    assert len(generated_rows) == 1
    assert str(generated_rows[0].path) == "src/generated.py"
    assert str(generated_rows[0].producer) == "ggen"


def test_every_iec_query_parses_and_executes_against_empty_graph() -> None:
    graph = Graph()
    for path in sorted(QUERIES.glob("*.rq")):
        # Executing against an empty graph proves parser/query compatibility
        # without pretending that any row exists.
        list(graph.query(path.read_text()))
