"""Semantic projection, coverage, lineage, and replay-manifest tests."""

from __future__ import annotations

import pytest

from autofde_lab.iec.coverage import assess_coverage
from autofde_lab.iec.engine import InverseEcosystemCompiler
from autofde_lab.iec.lineage import EvidenceLineage, LineageEdge
from autofde_lab.iec.manifest import MoonshotManifest, ToolIdentity
from autofde_lab.iec.model import ClaimCeiling, RepositorySubject
from autofde_lab.iec.observations import PassiveFile
from autofde_lab.iec.semantic_extractor import RepositorySemanticProjector


def subject(name: str, revision: str) -> RepositorySubject:
    return RepositorySubject(
        repository=name,
        revision=revision,
        default_branch="main",
    )


def analysis_fixture():
    compiler = InverseEcosystemCompiler()
    repo = subject("seanchatmangpt/example", "a" * 40)
    session = compiler.freeze((repo,))
    session = compiler.observe(
        session,
        repo,
        (
            PassiveFile("ontology/domain.ttl", b"@prefix ex: <urn:x:> ."),
            PassiveFile("src/generated.py", b"# GENERATED BY ggen\n"),
            PassiveFile("src/unknown.py", b"def f(): return 1\n"),
        ),
    )
    return session.analyses[0]


def test_repository_analysis_projects_to_semantic_graph() -> None:
    analysis = analysis_fixture()
    graph = RepositorySemanticProjector().project(analysis)

    repository_nodes = [node for node in graph.nodes if node.kind == "Repository"]
    artifact_nodes = [node for node in graph.nodes if node.kind == "Artifact"]
    generator_nodes = [node for node in graph.nodes if node.kind == "Generator"]

    assert len(repository_nodes) == 1
    assert len(artifact_nodes) == 3
    assert len(generator_nodes) == 1
    assert generator_nodes[0].key == "ggen"

    generated = next(
        node
        for node in artifact_nodes
        if dict(node.attributes)["path"] == "src/generated.py"
    )
    generated_edges = graph.outgoing(generated.node_id)
    assert any(edge.predicate == "generatedBy" for edge in generated_edges)


def test_coverage_preserves_unknown_paths() -> None:
    assessment = assess_coverage(analysis_fixture())
    assert assessment.total_artifacts == 3
    assert assessment.classified_artifacts == 2
    assert assessment.unknown_artifacts == 1
    assert assessment.unknown_paths == ("src/unknown.py",)
    assert assessment.coverage == pytest.approx(2 / 3)
    assert assessment.producer_coverage == 1.0


def test_lineage_tracks_ancestors_and_refuses_cycles() -> None:
    lineage = EvidenceLineage.build(
        (
            LineageEdge("observation", "claim", "supports"),
            LineageEdge("claim", "projection", "generates"),
            LineageEdge("projection", "receipt", "verifiedBy"),
        )
    )
    assert lineage.parents("claim") == ("observation",)
    assert lineage.ancestors("receipt") == frozenset(
        {"observation", "claim", "projection"}
    )

    with pytest.raises(ValueError, match="cyclic evidence lineage"):
        EvidenceLineage.build(
            (
                LineageEdge("a", "b", "supports"),
                LineageEdge("b", "a", "supports"),
            )
        )


def test_moonshot_manifest_binds_exact_tool_and_subject_identities() -> None:
    implementation = subject("seanchatmangpt/autofde-lab", "1" * 40)
    corpus = (
        subject("seanchatmangpt/ggen-create", "2" * 40),
        subject("seanchatmangpt/ggen_igniter", "3" * 40),
    )
    tools = (
        ToolIdentity(
            name="ggen-create",
            version="v26",
            source_revision="2" * 40,
        ),
        ToolIdentity(
            name="TLC",
            version="1",
            executable_digest="sha256:tlc",
        ),
    )
    manifest = MoonshotManifest(
        version="v26.9.23",
        implementation_subject=implementation,
        corpus_subjects=corpus,
        tools=tools,
        verifier_set_ids=("verifier-set",),
        claim_ceiling=ClaimCeiling.TRANSLATION_VALIDATED_FOR_EXACT_SUBJECT,
    )
    assert manifest.manifest_id
    assert manifest.authority == "NONE"


def test_moonshot_manifest_refuses_duplicate_repository_subjects() -> None:
    duplicate = subject("seanchatmangpt/a", "a" * 40)
    with pytest.raises(ValueError, match="duplicate repository subjects"):
        MoonshotManifest(
            version="v",
            implementation_subject=duplicate,
            corpus_subjects=(duplicate, duplicate),
            tools=(),
            verifier_set_ids=(),
            claim_ceiling=ClaimCeiling.STRUCTURAL_EQUIVALENCE_ONLY,
        )
