"""Domain-evidence registry -- real per-domain facts needed to drive the
generic OCEL episode runner (`scripts/run_domain_gymact_ocel_episode.py`) and
generic standalone verifier (`scripts/verify_domain_episode.py`).

Manufactured by `ggen sync run` from `ontology/domain-evidence.ttl` via
`queries/domain-evidence/registry.rq`: one `DomainEvidenceSpec` per real
`afl:DomainEvidenceSpec` individual, per
`docs/jira/2026-08-13-domain-maturity-l4/INDEX-AND-GGEN-DESIGN.md`'s
"autofde-domain-evidence-pack" design. Adding a new domain to the L4-push
pipeline means adding one new ontology individual, not writing a new script
or verifier -- the generic runner/verifier below consume this registry.

GENERATED by ggen. DO NOT EDIT BY HAND -- edit
`ontology/domain-evidence.ttl` and re-run `ggen sync run` from the repo root
to regenerate.
"""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class CapabilitySpec:
    """One DO/OBSERVE capability of a domain, with its precondition
    expression (a Python boolean expression evaluated with `state` and
    `action` bound)."""

    name: str
    consequence: str
    precondition_expr: str


@dataclass(frozen=True)
class DomainEvidenceSpec:
    """Real facts about one hub domain needed to generate/drive its OCEL
    episode + standalone verifier."""

    domain_name: str
    python_module_path: str
    domain_class_name: str
    bridge_module_path: str
    bridge_class_name: str
    goal_check_expr: str
    verify_mode: str
    evidence_out_path: str
    capabilities: tuple[CapabilitySpec, ...] = field(default_factory=tuple)


DOMAIN_EVIDENCE_REGISTRY: dict[str, DomainEvidenceSpec] = {

"terragoat": DomainEvidenceSpec(
        domain_name="terragoat",
        python_module_path="autofde_lab.hub.domain.terragoat.terragoat_remediation",
        domain_class_name="TerraGoatRemediation",
        bridge_module_path="",
        bridge_class_name="",
        goal_check_expr="len(state.open_findings) == 0",
        verify_mode="fresh-instance-replay",
        evidence_out_path="docs/evidence/terragoat/domain-evidence-episode.ocel.json",
        capabilities=(
            CapabilitySpec(name="close_finding", consequence="DO", precondition_expr="finding_id in state.open_findings"),
        ),
    ),
}
