"""Deterministic AtomVM Erlang projection for CMCA scheduling and reduction budgets.

Translates a CascadeAllocationPlan into an Erlang supervision / scheduler module
ready to execute on AtomVM embedded microcontrollers.
"""

from __future__ import annotations

from .contracts import CascadeAllocationPlan


def generate_atomvm_cmca_module(
    plan: CascadeAllocationPlan,
    *,
    module_name: str = "cmca_scheduler_v2030",
) -> str:
    """Generate standalone, portable Erlang source for an AtomVM supervisor."""
    lines: list[str] = [
        f"%% @doc Autogenerated AtomVM CMCA Scheduler Module: {module_name}",
        f"%% Plan ID: {plan.plan_id}",
        f"%% Plan Hash: {plan.plan_hash}",
        f"%% Tau: {plan.tau_temperature}",
        "-module(" + module_name + ").",
        "-export([get_plan/0, get_allocations/0, get_lanes/0, schedule_branch/1]).",
        "",
        "get_plan() ->",
        f'    #{{plan_id => <<"{plan.plan_id}">>,',
        f'       plan_hash => <<"{plan.plan_hash}">>,',
        f"       total_ticks => {plan.parent_budget.total_ticks},",
        f"       concurrency_lanes => {plan.parent_budget.concurrency_lanes}}}.",
        "",
        "get_allocations() ->",
        "    [",
    ]

    alloc_entries: list[str] = []
    for a in plan.allocations:
        entry = (
            f'      #{{branch_id => <<"{a.branch_id}">>,\n'
            f"        standing => {a.standing.value.lower()},\n"
            f"        ticks => {a.allocated_ticks},\n"
            f"        memory_bytes => {a.allocated_memory_bytes},\n"
            f"        depth => {a.verification_depth},\n"
            f"        priority_lane => {a.priority_lane}}}"
        )
        alloc_entries.append(entry)

    lines.append(",\n".join(alloc_entries))
    lines.extend(
        [
            "    ].",
            "",
            "get_lanes() ->",
            f"    {plan.parent_budget.concurrency_lanes}.",
            "",
            "schedule_branch(BranchId) when is_binary(BranchId) ->",
            "    case lists:filter(fun(#{branch_id := B}) -> B =:= BranchId end, get_allocations()) of",
            "        [Allocation | _] -> {ok, Allocation};",
            "        [] -> {error, not_found}",
            "    end.",
            "",
        ]
    )
    return "\n".join(lines)
