"""Formal contracts and cryptographic data structures for CMCA.

CMCA (Chatman Multifractal Cascade Allocation) determines the allocation of finite
resources (compute ticks, memory bytes, verification depth, consequence capacity)
across a candidate exploration frontier without premature single-branch collapse.
CMCA performs SELECT, never ambient DO.
"""

from __future__ import annotations

import hashlib
import json
from collections.abc import Mapping
from dataclasses import dataclass
from enum import Enum
from typing import Any


class AllocationStanding(str, Enum):
    ADMITTED = "ADMITTED"
    PRUNED = "PRUNED"
    DEFERRED = "DEFERRED"
    EXHAUSTED = "EXHAUSTED"


@dataclass(frozen=True, slots=True)
class ResourceBudget:
    """Multi-dimensional finite resource boundary for an exploration frontier."""

    total_ticks: int
    memory_bytes: int
    max_verification_depth: int
    consequence_risk_budget: float  # [0.0, 1.0] ceiling on aggregate risky consequence
    concurrency_lanes: int = 8  # aligned with Chatman constant 8

    def validate(self) -> None:
        if self.total_ticks <= 0:
            raise ValueError("total_ticks must be strictly positive")
        if self.memory_bytes <= 0:
            raise ValueError("memory_bytes must be strictly positive")
        if self.max_verification_depth < 0:
            raise ValueError("max_verification_depth cannot be negative")
        if not (0.0 <= self.consequence_risk_budget <= 1.0):
            raise ValueError("consequence_risk_budget must be in [0.0, 1.0]")
        if self.concurrency_lanes <= 0:
            raise ValueError("concurrency_lanes must be positive")


@dataclass(frozen=True, slots=True)
class CandidateBranch:
    """An exploration branch candidate generated by DfCM / Planners."""

    branch_id: str
    operator_id: str  # e.g., C8L model or policy ID
    world_id: str  # e.g., GymAct world or state projection
    state_id: str
    option_entropy: float  # Lawful future option entropy / volume
    estimated_cost: float  # Estimated baseline execution resource unit
    historical_yield: float = 1.0  # Historical verification payoff ratio
    metadata: Mapping[str, Any] | None = None

    @property
    def candidate_hash(self) -> str:
        blob = f"{self.branch_id}:{self.operator_id}:{self.world_id}:{self.state_id}:{self.option_entropy}:{self.estimated_cost}"
        return hashlib.sha256(blob.encode("utf-8")).hexdigest()


@dataclass(frozen=True, slots=True)
class BranchAllocation:
    """Assigned allocation of finite resource mass to a single candidate branch."""

    branch_id: str
    allocated_fraction: float  # [0.0, 1.0]
    allocated_ticks: int
    allocated_memory_bytes: int
    verification_depth: int
    standing: AllocationStanding
    priority_lane: int  # 0 to concurrency_lanes - 1


@dataclass(frozen=True, slots=True)
class CascadeAllocationPlan:
    """Cryptographic, content-bound manifest of a completed CMCA allocation."""

    plan_id: str
    parent_budget: ResourceBudget
    allocations: tuple[BranchAllocation, ...]
    total_option_value_preserved: float
    entropy: float

    @property
    def plan_hash(self) -> str:
        payload = {
            "plan_id": self.plan_id,
            "preserved": self.total_option_value_preserved,
            "entropy": self.entropy,
            "allocations": [
                {
                    "branch": a.branch_id,
                    "frac": round(a.allocated_fraction, 8),
                    "ticks": a.allocated_ticks,
                    "depth": a.verification_depth,
                    "standing": a.standing.value,
                }
                for a in self.allocations
            ],
        }
        dumped = json.dumps(payload, sort_keys=True, separators=(",", ":"))
        return hashlib.sha256(dumped.encode("utf-8")).hexdigest()


@dataclass(frozen=True, slots=True)
class AllocationReceipt:
    """Receipt tracking post-execution verification payoff to feedback into CMCA."""

    receipt_id: str
    plan_hash: str
    branch_id: str
    ticks_consumed: int
    consequence_observed: bool
    options_retained_actual: int
    payoff_score: float  # Options preserved / resources consumed ratio
