"""AtomVM Erlang projection generator for tiny semantic operators.

Generates pure, standalone Erlang targeting the AtomVM BEAM runtime with zero external
dependencies, integer arithmetic, and strict traceability back to O*.
"""

from __future__ import annotations

import shutil
import subprocess
from enum import Enum
from pathlib import Path

from .portable_compiler import PortableLinearWeights
from .tiny_operator import TinyOperatorManifest


class AtomVMStanding(str, Enum):
    """Execution standing levels for AtomVM Erlang projections."""

    GENERATED = "GENERATED"
    COMPILED = "COMPILED"
    EXECUTED = "EXECUTED"
    QUALIFIED = "QUALIFIED"
    UNSUPPORTED = "UNSUPPORTED"


def generate_atomvm_erlang_module(
    linear: PortableLinearWeights,
    manifest: TinyOperatorManifest,
    *,
    module_name: str = "semantic_operator_v26_9_14",
) -> str:
    """Generate deterministic Erlang source code compatible with AtomVM BEAM execution."""
    weights_lines: list[str] = []
    for class_idx, (w_row, bias) in enumerate(
        zip(linear.fixed_weights, linear.fixed_biases, strict=False)
    ):
        w_str = "[" + ", ".join(str(w) for w in w_row) + "]"
        weights_lines.append(f"        {{{w_str}, {bias}}}")
    weights_body = ",\n".join(weights_lines)

    iris_lines = [f'        <<"{iri}">>' for iri in manifest.output_semantic_iris]
    iris_body = ",\n".join(iris_lines)

    code = f"""%% Generated by AutoFDE Lab v26.9.14 - AtomVM Tiny Semantic Operator
%% Ontology Hash: {manifest.ontology_hash}
%% Manifest Hash: {manifest.manifest_hash}
-module({module_name}).
-export([predict/1, predict_iri/1, manifest/0, output_iris/0]).

manifest() ->
    #{"{"}
        ontology_hash => <<"{manifest.ontology_hash}">>,
        feature_schema_hash => <<"{manifest.feature_schema_hash}">>,
        manifest_hash => <<"{manifest.manifest_hash}">>,
        model_family => <<"{manifest.model_family}">>,
        model_revision => <<"{manifest.model_revision}">>,
        quantization => <<"{manifest.quantization.value}">>,
        input_dimensions => {manifest.input_dimensions},
        scale => {linear.scale}
    {"}"}.

output_iris() ->
    [
{iris_body}
    ].

weights_and_biases() ->
    [
{weights_body}
    ].

predict_iri(Features) when is_list(Features) ->
    Idx = predict(Features),
    lists:nth(Idx + 1, output_iris()).

predict(Features) when is_list(Features) ->
    Pairs = weights_and_biases(),
    Scores = [score_class(W, B, Features) || {{W, B}} <- Pairs],
    argmax(Scores, 0, -9223372036854775807, 0).

score_class(Weights, Bias, Features) ->
    score_dot(Weights, Features, Bias).

score_dot([], [], Acc) ->
    Acc;
score_dot([W | Wr], [F | Fr], Acc) ->
    score_dot(Wr, Fr, Acc + (W * F)).

argmax([], _CurrIdx, _MaxScore, BestIdx) ->
    BestIdx;
argmax([Score | Rest], CurrIdx, MaxScore, BestIdx) ->
    case Score > MaxScore of
        true ->
            argmax(Rest, CurrIdx + 1, Score, CurrIdx);
        false ->
            argmax(Rest, CurrIdx + 1, MaxScore, BestIdx)
    end.
"""
    return code


def compile_and_test_erlang(
    erl_code: str,
    test_vector: list[int],
    *,
    module_name: str = "semantic_operator_v26_9_14",
    work_dir: Path | None = None,
) -> tuple[AtomVMStanding, int | None]:
    """Inspect and conditionally compile/execute the generated Erlang module if tools exist."""
    erlc_path = shutil.which("erlc")
    erl_path = shutil.which("erl")

    if not erlc_path or not erl_path:
        return AtomVMStanding.GENERATED, None

    import tempfile

    target_dir = work_dir or Path(tempfile.mkdtemp(prefix="atomvm_test_"))
    erl_file = target_dir / f"{module_name}.erl"
    erl_file.write_text(erl_code, encoding="utf-8")

    try:
        # Compile
        compile_res = subprocess.run(
            [erlc_path, str(erl_file)],
            cwd=str(target_dir),
            capture_output=True,
            timeout=10,
            check=False,
        )
        if compile_res.returncode != 0:
            return AtomVMStanding.GENERATED, None

        # Execute single prediction call
        vec_str = "[" + ", ".join(str(x) for x in test_vector) + "]"
        eval_expr = f'io:format("~p~n", [{module_name}:predict({vec_str})]), halt(0).'
        exec_res = subprocess.run(
            [erl_path, "-noshell", "-pa", str(target_dir), "-eval", eval_expr],
            cwd=str(target_dir),
            capture_output=True,
            timeout=10,
            text=True,
            check=False,
        )
        if exec_res.returncode == 0 and exec_res.stdout.strip().isdigit():
            predicted_class = int(exec_res.stdout.strip())
            return AtomVMStanding.EXECUTED, predicted_class

        return AtomVMStanding.COMPILED, None
    except (subprocess.SubprocessError, OSError):
        return AtomVMStanding.GENERATED, None
