# GENERATED by ggen sync from ontology/*.ttl + ontology/python-projection.ttl.
# DO NOT EDIT BY HAND.
# ruff: noqa: I001

"""Canonical Python projection of the AutoFDE Lab semantic constitution."""

from ._base import SemanticEntity

from .authority import Actuation

from .authority import AuthorityEnvelope

from .evidence import Artifact

from .evidence import ArtifactManifest

from .evidence import DependencyRevision

from .evidence import EvidenceWitness

from .evidence import Level4Witness

from .evidence import Observer

from .evidence import Postcondition

from .evidence import PostconditionObservation

from .evidence import Receipt

from .evidence import ReceiptDAG

from .evidence import Replay

from .evidence import SourceRevision

from .evidence import VerifierRun

from .interop import ExternalRepresentation

from .interop import InteropAdapter

from .interop import InteropContract

from .interop import InteropContractReceipt

from .interop import LossReport

from .interop import Projection

from .interop import SemanticLoss

from .lab import Capability

from .lab import Experiment

from .lab import Goal

from .lab import Gym

from .lab import Invariant

from .lab import Perturbation

from .lab import Resource

from .lab import Trial

from .manufacture import CanonicalSourceArtifact

from .manufacture import ManufactureReceipt

from .manufacture import ManufactureRule

from .manufacture import ManufactureRun

from .manufacture import SemanticConstitution

from .planning import CandidateSet

from .planning import Critique

from .planning import Disagreement

from .planning import DiscriminatingProbe

from .planning import GovernedCandidate

from .planning import PlanCandidate

from .planning import Planner

from .planning import PlannerAttempt

from .planning import PlanningProblem

from .planning import Validation

from .process import ChoiceGraph

from .process import OrderEdge

from .process import POWLCommitment

from .process import POWLProcess

from .process import PartialOrderComposite

from .process import ProcessNode

from .process import SilentTransition

from .process import TransitionNode

from .standing import Refusal

from .standing import StandingAssertion

from .standing import StandingValue

from .world import AdmittedObservation

from .world import Environment

from .world import Observation

from .world import ObservationAdmission

from .world import World

from .world import WorldState

from .registry import CLASS_BY_IRI, class_for_rdf_type, entity_from_rdf_type
from .terms import PROPERTY_IRI_BY_NAME, STANDING_VALUE_IRI
from .validation import CONSTITUTION_FILES, SHAPE_FILES, load_constitution, validate_graph

__all__ = [
    "SemanticEntity",

    "Actuation",

    "AuthorityEnvelope",

    "Artifact",

    "ArtifactManifest",

    "DependencyRevision",

    "EvidenceWitness",

    "Level4Witness",

    "Observer",

    "Postcondition",

    "PostconditionObservation",

    "Receipt",

    "ReceiptDAG",

    "Replay",

    "SourceRevision",

    "VerifierRun",

    "ExternalRepresentation",

    "InteropAdapter",

    "InteropContract",

    "InteropContractReceipt",

    "LossReport",

    "Projection",

    "SemanticLoss",

    "Capability",

    "Experiment",

    "Goal",

    "Gym",

    "Invariant",

    "Perturbation",

    "Resource",

    "Trial",

    "CanonicalSourceArtifact",

    "ManufactureReceipt",

    "ManufactureRule",

    "ManufactureRun",

    "SemanticConstitution",

    "CandidateSet",

    "Critique",

    "Disagreement",

    "DiscriminatingProbe",

    "GovernedCandidate",

    "PlanCandidate",

    "Planner",

    "PlannerAttempt",

    "PlanningProblem",

    "Validation",

    "ChoiceGraph",

    "OrderEdge",

    "POWLCommitment",

    "POWLProcess",

    "PartialOrderComposite",

    "ProcessNode",

    "SilentTransition",

    "TransitionNode",

    "Refusal",

    "StandingAssertion",

    "StandingValue",

    "AdmittedObservation",

    "Environment",

    "Observation",

    "ObservationAdmission",

    "World",

    "WorldState",

    "CLASS_BY_IRI",
    "class_for_rdf_type",
    "entity_from_rdf_type",
    "PROPERTY_IRI_BY_NAME",
    "STANDING_VALUE_IRI",
    "CONSTITUTION_FILES",
    "SHAPE_FILES",
    "load_constitution",
    "validate_graph",
]
