# GENERATED by ggen sync from ontology/*.ttl + ontology/python-projection.ttl.
# DO NOT EDIT BY HAND.

"""Shared runtime substrate for ggen-manufactured semantic constitution types."""

from __future__ import annotations

from dataclasses import dataclass, field
from types import MappingProxyType
from typing import ClassVar, Mapping


@dataclass(frozen=True, slots=True, kw_only=True)
class SemanticEntity:
    """Immutable RDF-identity carrier for one ontology-backed semantic type."""

    iri: str
    values: Mapping[str, object] = field(default_factory=dict)

    RDF_TYPE: ClassVar[str] = "urn:autofde-lab:SemanticEntity"

    def __post_init__(self) -> None:
        object.__setattr__(self, "values", MappingProxyType(dict(self.values)))

    @classmethod
    def rdf_type(cls) -> str:
        return cls.RDF_TYPE

    def get(self, property_iri: str, default: object = None) -> object:
        return self.values.get(property_iri, default)

    def require(self, property_iri: str) -> object:
        if property_iri not in self.values:
            raise KeyError(f"{self.RDF_TYPE} requires property {property_iri}")
        return self.values[property_iri]

    def with_values(self, **values: object) -> "SemanticEntity":
        merged = dict(self.values)
        merged.update(values)
        return type(self)(iri=self.iri, values=merged)

    def as_bindings(self) -> dict[str, object]:
        return {"@id": self.iri, "@type": self.RDF_TYPE, **dict(self.values)}
