# GENERATED by ggen sync from ontology/*.ttl + ontology/python-projection.ttl.
# DO NOT EDIT BY HAND.

"""Ontology-backed semantic types manufactured from the admitted RDF graph."""

from __future__ import annotations

from ._base import SemanticEntity



class AuthorityEnvelope(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:AuthorityEnvelope``."""

    RDF_TYPE = "urn:autofde-lab:AuthorityEnvelope"



class Actuation(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:Actuation``."""

    RDF_TYPE = "urn:autofde-lab:Actuation"



__all__ = [

    "AuthorityEnvelope",

    "Actuation",

]
