# GENERATED by ggen sync from ontology/*.ttl + ontology/python-projection.ttl.
# DO NOT EDIT BY HAND.

"""Ontology-backed semantic types manufactured from the admitted RDF graph."""

from __future__ import annotations

from ._base import SemanticEntity



class Postcondition(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:Postcondition``."""

    RDF_TYPE = "urn:autofde-lab:Postcondition"



class Observer(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:Observer``."""

    RDF_TYPE = "urn:autofde-lab:Observer"



class PostconditionObservation(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:PostconditionObservation``."""

    RDF_TYPE = "urn:autofde-lab:PostconditionObservation"



class Receipt(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:Receipt``."""

    RDF_TYPE = "urn:autofde-lab:Receipt"



class ReceiptDAG(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:ReceiptDAG``."""

    RDF_TYPE = "urn:autofde-lab:ReceiptDAG"



class Replay(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:Replay``."""

    RDF_TYPE = "urn:autofde-lab:Replay"



class Artifact(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:Artifact``."""

    RDF_TYPE = "urn:autofde-lab:Artifact"



class ArtifactManifest(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:ArtifactManifest``."""

    RDF_TYPE = "urn:autofde-lab:ArtifactManifest"



class SourceRevision(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:SourceRevision``."""

    RDF_TYPE = "urn:autofde-lab:SourceRevision"



class DependencyRevision(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:DependencyRevision``."""

    RDF_TYPE = "urn:autofde-lab:DependencyRevision"



class VerifierRun(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:VerifierRun``."""

    RDF_TYPE = "urn:autofde-lab:VerifierRun"



class EvidenceWitness(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:EvidenceWitness``."""

    RDF_TYPE = "urn:autofde-lab:EvidenceWitness"



class Level4Witness(EvidenceWitness):
    """Generated semantic type for ``urn:autofde-lab:Level4Witness``."""

    RDF_TYPE = "urn:autofde-lab:Level4Witness"



__all__ = [

    "Postcondition",

    "Observer",

    "PostconditionObservation",

    "Receipt",

    "ReceiptDAG",

    "Replay",

    "Artifact",

    "ArtifactManifest",

    "SourceRevision",

    "DependencyRevision",

    "VerifierRun",

    "EvidenceWitness",

    "Level4Witness",

]
