# GENERATED by ggen sync from ontology/*.ttl + ontology/python-projection.ttl.
# DO NOT EDIT BY HAND.

"""Ontology-backed semantic types manufactured from the admitted RDF graph."""

from __future__ import annotations

from ._base import SemanticEntity


class InteropContract(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:InteropContract``."""

    RDF_TYPE = "urn:autofde-lab:InteropContract"


class InteropAdapter(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:InteropAdapter``."""

    RDF_TYPE = "urn:autofde-lab:InteropAdapter"


class ExternalRepresentation(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:ExternalRepresentation``."""

    RDF_TYPE = "urn:autofde-lab:ExternalRepresentation"


class Projection(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:Projection``."""

    RDF_TYPE = "urn:autofde-lab:Projection"


class SemanticLoss(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:SemanticLoss``."""

    RDF_TYPE = "urn:autofde-lab:SemanticLoss"


class LossReport(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:LossReport``."""

    RDF_TYPE = "urn:autofde-lab:LossReport"


class InteropContractReceipt(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:InteropContractReceipt``."""

    RDF_TYPE = "urn:autofde-lab:InteropContractReceipt"


__all__ = [
    "InteropContract",
    "InteropAdapter",
    "ExternalRepresentation",
    "Projection",
    "SemanticLoss",
    "LossReport",
    "InteropContractReceipt",
]
