# GENERATED by ggen sync from ontology/*.ttl + ontology/python-projection.ttl.
# DO NOT EDIT BY HAND.

"""Ontology-backed semantic types manufactured from the admitted RDF graph."""

from __future__ import annotations

from ._base import SemanticEntity



class Gym(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:Gym``."""

    RDF_TYPE = "urn:autofde-lab:Gym"



class Trial(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:Trial``."""

    RDF_TYPE = "urn:autofde-lab:Trial"



class Experiment(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:Experiment``."""

    RDF_TYPE = "urn:autofde-lab:Experiment"



class Goal(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:Goal``."""

    RDF_TYPE = "urn:autofde-lab:Goal"



class Invariant(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:Invariant``."""

    RDF_TYPE = "urn:autofde-lab:Invariant"



class Resource(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:Resource``."""

    RDF_TYPE = "urn:autofde-lab:Resource"



class Capability(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:Capability``."""

    RDF_TYPE = "urn:autofde-lab:Capability"



class Perturbation(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:Perturbation``."""

    RDF_TYPE = "urn:autofde-lab:Perturbation"



__all__ = [

    "Gym",

    "Trial",

    "Experiment",

    "Goal",

    "Invariant",

    "Resource",

    "Capability",

    "Perturbation",

]
