# GENERATED by ggen sync from ontology/*.ttl + ontology/python-projection.ttl.
# DO NOT EDIT BY HAND.

"""Ontology-backed semantic types manufactured from the admitted RDF graph."""

from __future__ import annotations

from ._base import SemanticEntity



class SemanticConstitution(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:SemanticConstitution``."""

    RDF_TYPE = "urn:autofde-lab:SemanticConstitution"



class ManufactureRule(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:ManufactureRule``."""

    RDF_TYPE = "urn:autofde-lab:ManufactureRule"



class ManufactureRun(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:ManufactureRun``."""

    RDF_TYPE = "urn:autofde-lab:ManufactureRun"



class CanonicalSourceArtifact(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:CanonicalSourceArtifact``."""

    RDF_TYPE = "urn:autofde-lab:CanonicalSourceArtifact"



class ManufactureReceipt(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:ManufactureReceipt``."""

    RDF_TYPE = "urn:autofde-lab:ManufactureReceipt"



__all__ = [

    "SemanticConstitution",

    "ManufactureRule",

    "ManufactureRun",

    "CanonicalSourceArtifact",

    "ManufactureReceipt",

]
