# GENERATED by ggen sync from ontology/*.ttl + ontology/python-projection.ttl.
# DO NOT EDIT BY HAND.

"""Ontology-backed semantic types manufactured from the admitted RDF graph."""

from __future__ import annotations

from ._base import SemanticEntity



class PlanningProblem(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:PlanningProblem``."""

    RDF_TYPE = "urn:autofde-lab:PlanningProblem"



class Planner(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:Planner``."""

    RDF_TYPE = "urn:autofde-lab:Planner"



class PlannerAttempt(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:PlannerAttempt``."""

    RDF_TYPE = "urn:autofde-lab:PlannerAttempt"



class PlanCandidate(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:PlanCandidate``."""

    RDF_TYPE = "urn:autofde-lab:PlanCandidate"



class CandidateSet(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:CandidateSet``."""

    RDF_TYPE = "urn:autofde-lab:CandidateSet"



class Critique(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:Critique``."""

    RDF_TYPE = "urn:autofde-lab:Critique"



class Validation(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:Validation``."""

    RDF_TYPE = "urn:autofde-lab:Validation"



class GovernedCandidate(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:GovernedCandidate``."""

    RDF_TYPE = "urn:autofde-lab:GovernedCandidate"



class Disagreement(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:Disagreement``."""

    RDF_TYPE = "urn:autofde-lab:Disagreement"



class DiscriminatingProbe(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:DiscriminatingProbe``."""

    RDF_TYPE = "urn:autofde-lab:DiscriminatingProbe"



__all__ = [

    "PlanningProblem",

    "Planner",

    "PlannerAttempt",

    "PlanCandidate",

    "CandidateSet",

    "Critique",

    "Validation",

    "GovernedCandidate",

    "Disagreement",

    "DiscriminatingProbe",

]
