# GENERATED by ggen sync from ontology/*.ttl + ontology/python-projection.ttl.
# DO NOT EDIT BY HAND.

"""Ontology-backed semantic types manufactured from the admitted RDF graph."""

from __future__ import annotations

from ._base import SemanticEntity



class POWLProcess(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:POWLProcess``."""

    RDF_TYPE = "urn:autofde-lab:POWLProcess"



class ProcessNode(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:ProcessNode``."""

    RDF_TYPE = "urn:autofde-lab:ProcessNode"



class TransitionNode(ProcessNode):
    """Generated semantic type for ``urn:autofde-lab:TransitionNode``."""

    RDF_TYPE = "urn:autofde-lab:TransitionNode"



class SilentTransition(TransitionNode):
    """Generated semantic type for ``urn:autofde-lab:SilentTransition``."""

    RDF_TYPE = "urn:autofde-lab:SilentTransition"



class PartialOrderComposite(ProcessNode):
    """Generated semantic type for ``urn:autofde-lab:PartialOrderComposite``."""

    RDF_TYPE = "urn:autofde-lab:PartialOrderComposite"



class ChoiceGraph(ProcessNode):
    """Generated semantic type for ``urn:autofde-lab:ChoiceGraph``."""

    RDF_TYPE = "urn:autofde-lab:ChoiceGraph"



class OrderEdge(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:OrderEdge``."""

    RDF_TYPE = "urn:autofde-lab:OrderEdge"



class POWLCommitment(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:POWLCommitment``."""

    RDF_TYPE = "urn:autofde-lab:POWLCommitment"



__all__ = [

    "POWLProcess",

    "ProcessNode",

    "TransitionNode",

    "SilentTransition",

    "PartialOrderComposite",

    "ChoiceGraph",

    "OrderEdge",

    "POWLCommitment",

]
