# GENERATED by ggen sync from ontology/*.ttl + ontology/python-projection.ttl.
# DO NOT EDIT BY HAND.

"""RDF-type registry for the ggen-manufactured semantic constitution."""

from __future__ import annotations

from . import authority as _authority
from . import evidence as _evidence
from . import interop as _interop
from . import lab as _lab
from . import manufacture as _manufacture
from . import planning as _planning
from . import process as _process
from . import standing as _standing
from . import world as _world
from ._base import SemanticEntity

CLASS_BY_IRI: dict[str, type[SemanticEntity]] = {

    "urn:autofde-lab:AuthorityEnvelope": _authority.AuthorityEnvelope,

    "urn:autofde-lab:Actuation": _authority.Actuation,

    "urn:autofde-lab:Postcondition": _evidence.Postcondition,

    "urn:autofde-lab:Observer": _evidence.Observer,

    "urn:autofde-lab:PostconditionObservation": _evidence.PostconditionObservation,

    "urn:autofde-lab:Receipt": _evidence.Receipt,

    "urn:autofde-lab:ReceiptDAG": _evidence.ReceiptDAG,

    "urn:autofde-lab:Replay": _evidence.Replay,

    "urn:autofde-lab:Artifact": _evidence.Artifact,

    "urn:autofde-lab:ArtifactManifest": _evidence.ArtifactManifest,

    "urn:autofde-lab:SourceRevision": _evidence.SourceRevision,

    "urn:autofde-lab:DependencyRevision": _evidence.DependencyRevision,

    "urn:autofde-lab:VerifierRun": _evidence.VerifierRun,

    "urn:autofde-lab:EvidenceWitness": _evidence.EvidenceWitness,

    "urn:autofde-lab:Level4Witness": _evidence.Level4Witness,

    "urn:autofde-lab:InteropContract": _interop.InteropContract,

    "urn:autofde-lab:InteropAdapter": _interop.InteropAdapter,

    "urn:autofde-lab:ExternalRepresentation": _interop.ExternalRepresentation,

    "urn:autofde-lab:Projection": _interop.Projection,

    "urn:autofde-lab:SemanticLoss": _interop.SemanticLoss,

    "urn:autofde-lab:LossReport": _interop.LossReport,

    "urn:autofde-lab:InteropContractReceipt": _interop.InteropContractReceipt,

    "urn:autofde-lab:Gym": _lab.Gym,

    "urn:autofde-lab:Trial": _lab.Trial,

    "urn:autofde-lab:Experiment": _lab.Experiment,

    "urn:autofde-lab:Goal": _lab.Goal,

    "urn:autofde-lab:Invariant": _lab.Invariant,

    "urn:autofde-lab:Resource": _lab.Resource,

    "urn:autofde-lab:Capability": _lab.Capability,

    "urn:autofde-lab:Perturbation": _lab.Perturbation,

    "urn:autofde-lab:SemanticConstitution": _manufacture.SemanticConstitution,

    "urn:autofde-lab:ManufactureRule": _manufacture.ManufactureRule,

    "urn:autofde-lab:ManufactureRun": _manufacture.ManufactureRun,

    "urn:autofde-lab:CanonicalSourceArtifact": _manufacture.CanonicalSourceArtifact,

    "urn:autofde-lab:ManufactureReceipt": _manufacture.ManufactureReceipt,

    "urn:autofde-lab:PlanningProblem": _planning.PlanningProblem,

    "urn:autofde-lab:Planner": _planning.Planner,

    "urn:autofde-lab:PlannerAttempt": _planning.PlannerAttempt,

    "urn:autofde-lab:PlanCandidate": _planning.PlanCandidate,

    "urn:autofde-lab:CandidateSet": _planning.CandidateSet,

    "urn:autofde-lab:Critique": _planning.Critique,

    "urn:autofde-lab:Validation": _planning.Validation,

    "urn:autofde-lab:GovernedCandidate": _planning.GovernedCandidate,

    "urn:autofde-lab:Disagreement": _planning.Disagreement,

    "urn:autofde-lab:DiscriminatingProbe": _planning.DiscriminatingProbe,

    "urn:autofde-lab:POWLProcess": _process.POWLProcess,

    "urn:autofde-lab:ProcessNode": _process.ProcessNode,

    "urn:autofde-lab:TransitionNode": _process.TransitionNode,

    "urn:autofde-lab:SilentTransition": _process.SilentTransition,

    "urn:autofde-lab:PartialOrderComposite": _process.PartialOrderComposite,

    "urn:autofde-lab:ChoiceGraph": _process.ChoiceGraph,

    "urn:autofde-lab:OrderEdge": _process.OrderEdge,

    "urn:autofde-lab:POWLCommitment": _process.POWLCommitment,

    "urn:autofde-lab:StandingValue": _standing.StandingValue,

    "urn:autofde-lab:StandingAssertion": _standing.StandingAssertion,

    "urn:autofde-lab:Refusal": _standing.Refusal,

    "urn:autofde-lab:World": _world.World,

    "urn:autofde-lab:WorldState": _world.WorldState,

    "urn:autofde-lab:Environment": _world.Environment,

    "urn:autofde-lab:Observation": _world.Observation,

    "urn:autofde-lab:AdmittedObservation": _world.AdmittedObservation,

    "urn:autofde-lab:ObservationAdmission": _world.ObservationAdmission,

}


def class_for_rdf_type(rdf_type: str) -> type[SemanticEntity]:
    """Return the generated Python class for an admitted RDF type."""
    try:
        return CLASS_BY_IRI[rdf_type]
    except KeyError as exc:
        raise KeyError(
            f"No generated Python projection for RDF type {rdf_type}"
        ) from exc


def entity_from_rdf_type(
    rdf_type: str,
    *,
    iri: str,
    values: dict[str, object] | None = None,
) -> SemanticEntity:
    """Construct the generated semantic carrier for ``rdf_type``."""
    cls = class_for_rdf_type(rdf_type)
    return cls(iri=iri, values=values or {})
