# GENERATED by ggen sync from ontology/*.ttl + ontology/python-projection.ttl.
# DO NOT EDIT BY HAND.

"""Ontology-backed semantic types manufactured from the admitted RDF graph."""

from __future__ import annotations

from ._base import SemanticEntity


class StandingValue(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:StandingValue``."""

    RDF_TYPE = "urn:autofde-lab:StandingValue"


class StandingAssertion(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:StandingAssertion``."""

    RDF_TYPE = "urn:autofde-lab:StandingAssertion"


class Refusal(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:Refusal``."""

    RDF_TYPE = "urn:autofde-lab:Refusal"


__all__ = [
    "StandingValue",
    "StandingAssertion",
    "Refusal",
]
