# GENERATED by ggen sync from ontology/*.ttl + ontology/python-projection.ttl.
# DO NOT EDIT BY HAND.

"""Canonical RDF term IRIs projected from the semantic constitution."""PROPERTY_IRI_BY_NAME = {

    "aboutState": "urn:autofde-lab:aboutState",

    "actsOnEnvironment": "urn:autofde-lab:actsOnEnvironment",

    "actuation": "urn:autofde-lab:actuation",

    "adapterRevision": "urn:autofde-lab:adapterRevision",

    "admitsObservation": "urn:autofde-lab:admitsObservation",

    "admittedFromCandidateSet": "urn:autofde-lab:admittedFromCandidateSet",

    "affectedByPerturbation": "urn:autofde-lab:affectedByPerturbation",

    "afterNode": "urn:autofde-lab:afterNode",

    "afterState": "urn:autofde-lab:afterState",

    "assertsPostcondition": "urn:autofde-lab:assertsPostcondition",

    "attemptedBy": "urn:autofde-lab:attemptedBy",

    "authority": "urn:autofde-lab:authority",

    "authorityCapability": "urn:autofde-lab:authorityCapability",

    "authoritySubject": "urn:autofde-lab:authoritySubject",

    "authorizedBy": "urn:autofde-lab:authorizedBy",

    "authorizesActuation": "urn:autofde-lab:authorizesActuation",

    "beforeNode": "urn:autofde-lab:beforeNode",

    "beforeState": "urn:autofde-lab:beforeState",

    "belongsToTrial": "urn:autofde-lab:belongsToTrial",

    "bindsEntity": "urn:autofde-lab:bindsEntity",

    "candidateForTrial": "urn:autofde-lab:candidateForTrial",

    "canonicalProjectPath": "urn:autofde-lab:canonicalProjectPath",

    "causedByReceipt": "urn:autofde-lab:causedByReceipt",

    "commitment": "urn:autofde-lab:commitment",

    "commitsTo": "urn:autofde-lab:commitsTo",

    "committedProcess": "urn:autofde-lab:committedProcess",

    "containsCandidate": "urn:autofde-lab:containsCandidate",

    "containsReceipt": "urn:autofde-lab:containsReceipt",

    "contractReceiptFor": "urn:autofde-lab:contractReceiptFor",

    "critiquesCandidate": "urn:autofde-lab:critiquesCandidate",

    "dependencyRevision": "urn:autofde-lab:dependencyRevision",

    "derivedByVerifier": "urn:autofde-lab:derivedByVerifier",

    "derivedFromObservation": "urn:autofde-lab:derivedFromObservation",

    "derivedFromWitness": "urn:autofde-lab:derivedFromWitness",

    "designedFromDisagreement": "urn:autofde-lab:designedFromDisagreement",

    "digest": "urn:autofde-lab:digest",

    "evidencesActuation": "urn:autofde-lab:evidencesActuation",

    "evidencesObservation": "urn:autofde-lab:evidencesObservation",

    "exercisesCapability": "urn:autofde-lab:exercisesCapability",

    "externalRevision": "urn:autofde-lab:externalRevision",

    "governedCandidate": "urn:autofde-lab:governedCandidate",

    "governsCandidate": "urn:autofde-lab:governsCandidate",

    "hasCapability": "urn:autofde-lab:hasCapability",

    "hasChildNode": "urn:autofde-lab:hasChildNode",

    "hasGoal": "urn:autofde-lab:hasGoal",

    "hasInvariant": "urn:autofde-lab:hasInvariant",

    "hasOrderEdge": "urn:autofde-lab:hasOrderEdge",

    "hasResource": "urn:autofde-lab:hasResource",

    "hasRootNode": "urn:autofde-lab:hasRootNode",

    "hasWorld": "urn:autofde-lab:hasWorld",

    "lossReportFor": "urn:autofde-lab:lossReportFor",

    "manifest": "urn:autofde-lab:manifest",

    "manifestsArtifact": "urn:autofde-lab:manifestsArtifact",

    "manufacturesArtifact": "urn:autofde-lab:manufacturesArtifact",

    "observedFrom": "urn:autofde-lab:observedFrom",

    "observesActuation": "urn:autofde-lab:observesActuation",

    "performedBy": "urn:autofde-lab:performedBy",

    "perturbsWorld": "urn:autofde-lab:perturbsWorld",

    "postconditionObservation": "urn:autofde-lab:postconditionObservation",

    "precedes": "urn:autofde-lab:precedes",

    "preservesNode": "urn:autofde-lab:preservesNode",

    "producedByAdapter": "urn:autofde-lab:producedByAdapter",

    "producedCandidate": "urn:autofde-lab:producedCandidate",

    "projectsRepresentation": "urn:autofde-lab:projectsRepresentation",

    "pythonModule": "urn:autofde-lab:pythonModule",

    "pythonOrder": "urn:autofde-lab:pythonOrder",

    "readsManifest": "urn:autofde-lab:readsManifest",

    "realizesCommitment": "urn:autofde-lab:realizesCommitment",

    "receiptDag": "urn:autofde-lab:receiptDag",

    "receiptForManufacture": "urn:autofde-lab:receiptForManufacture",

    "recordsDisagreement": "urn:autofde-lab:recordsDisagreement",

    "refusalCode": "urn:autofde-lab:refusalCode",

    "refusalReason": "urn:autofde-lab:refusalReason",

    "repairOf": "urn:autofde-lab:repairOf",

    "replay": "urn:autofde-lab:replay",

    "replayOfTrial": "urn:autofde-lab:replayOfTrial",

    "replaysReceipt": "urn:autofde-lab:replaysReceipt",

    "reportsLoss": "urn:autofde-lab:reportsLoss",

    "semanticsPreserved": "urn:autofde-lab:semanticsPreserved",

    "singleUse": "urn:autofde-lab:singleUse",

    "solvesProblem": "urn:autofde-lab:solvesProblem",

    "sourceRevision": "urn:autofde-lab:sourceRevision",

    "standingSubject": "urn:autofde-lab:standingSubject",

    "standingValue": "urn:autofde-lab:standingValue",

    "targetsRepresentation": "urn:autofde-lab:targetsRepresentation",

    "trialId": "urn:autofde-lab:trialId",

    "usesConstitution": "urn:autofde-lab:usesConstitution",

    "usesContract": "urn:autofde-lab:usesContract",

    "usesManufactureRule": "urn:autofde-lab:usesManufactureRule",

    "validFrom": "urn:autofde-lab:validFrom",

    "validUntil": "urn:autofde-lab:validUntil",

    "validatesCandidate": "urn:autofde-lab:validatesCandidate",

    "witnessFor": "urn:autofde-lab:witnessFor",

}

STANDING_VALUE_IRI = {

    "ALIVE": "urn:autofde-lab:ALIVE",

    "BLOCKED": "urn:autofde-lab:BLOCKED",

    "BUILD_BROKEN": "urn:autofde-lab:BUILD_BROKEN",

    "PARTIAL_ALIVE": "urn:autofde-lab:PARTIAL_ALIVE",

    "UNKNOWN": "urn:autofde-lab:UNKNOWN",

    "UNSUPPORTED": "urn:autofde-lab:UNSUPPORTED",

}
