# GENERATED by ggen sync from ontology/*.ttl + ontology/python-projection.ttl.
# DO NOT EDIT BY HAND.

"""Runtime RDF/SHACL validation over the semantic constitution.

The imports are intentionally lazy so the base planning package remains importable
without the optional RDF validation extra.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

CONSTITUTION_FILES = (
    "ontology/lab.ttl",
    "ontology/world.ttl",
    "ontology/planning.ttl",
    "ontology/process.ttl",
    "ontology/authority.ttl",
    "ontology/evidence.ttl",
    "ontology/standing.ttl",
    "ontology/interop.ttl",
    "ontology/manufacture.ttl",
    "ontology/python-projection.ttl",
)

SHAPE_FILES = (
    "ontology/shapes/planning.shacl.ttl",
    "ontology/shapes/authority.shacl.ttl",
    "ontology/shapes/level4.shacl.ttl",
)


def _repo_root(root: str | Path | None) -> Path:
    if root is not None:
        return Path(root)
    return Path(__file__).resolve().parents[3]


def load_constitution(root: str | Path | None = None) -> Any:
    """Load all constitution graphs into one rdflib Graph."""
    try:
        from rdflib import Graph
    except ImportError as exc:
        raise RuntimeError("rdflib is required; install autofde-lab[ofmf]") from exc

    graph = Graph()
    base = _repo_root(root)
    for relative in CONSTITUTION_FILES:
        graph.parse(base / relative, format="turtle")
    return graph


def validate_graph(data_graph: Any, root: str | Path | None = None) -> tuple[bool, str]:
    """Validate ``data_graph`` against the constitution's SHACL boundary laws."""
    try:
        from pyshacl import validate
        from rdflib import Graph
    except ImportError as exc:
        raise RuntimeError(
            "pyshacl and rdflib are required; install autofde-lab[ofmf]"
        ) from exc

    base = _repo_root(root)
    shapes = Graph()
    for relative in SHAPE_FILES:
        shapes.parse(base / relative, format="turtle")

    conforms, _report_graph, report_text = validate(
        data_graph,
        shacl_graph=shapes,
        ont_graph=load_constitution(base),
        inference="rdfs",
        abort_on_first=False,
        allow_infos=True,
        allow_warnings=True,
    )
    return bool(conforms), str(report_text)
