# GENERATED by ggen sync from ontology/*.ttl + ontology/python-projection.ttl.
# DO NOT EDIT BY HAND.

"""Ontology-backed semantic types manufactured from the admitted RDF graph."""

from __future__ import annotations

from ._base import SemanticEntity


class World(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:World``."""

    RDF_TYPE = "urn:autofde-lab:World"


class WorldState(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:WorldState``."""

    RDF_TYPE = "urn:autofde-lab:WorldState"


class Environment(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:Environment``."""

    RDF_TYPE = "urn:autofde-lab:Environment"


class Observation(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:Observation``."""

    RDF_TYPE = "urn:autofde-lab:Observation"


class AdmittedObservation(Observation):
    """Generated semantic type for ``urn:autofde-lab:AdmittedObservation``."""

    RDF_TYPE = "urn:autofde-lab:AdmittedObservation"


class ObservationAdmission(SemanticEntity):
    """Generated semantic type for ``urn:autofde-lab:ObservationAdmission``."""

    RDF_TYPE = "urn:autofde-lab:ObservationAdmission"


__all__ = [
    "World",
    "WorldState",
    "Environment",
    "Observation",
    "AdmittedObservation",
    "ObservationAdmission",
]
