"""IEC-003: deterministic repository census from the git object database.

`census()` enumerates one exact commit with `git ls-tree -r` and reads every blob
through `git cat-file --batch`. The working tree is never consulted, so the census
is a function of `(repository, commit)` alone and replays byte-identically.

Each file receives:

* structural facts (`OBSERVED`): mode, blob id, size, binary-ness, language;
* an origin (`ArtifactOrigin`) reached only by the rules below, each carrying the
  `EvidenceStrength` it rests on.

Origin rules, strongest first. Anything no rule reaches is `UNKNOWN` -- never
`HANDWRITTEN_IRREDUCIBLE`. "No generator marker" is absence of evidence, and
`.claude/rules/absence-is-not-evidence.md` forbids reading it as handwritten.

1. gitlink entries (mode 160000) are `EXTERNAL_VENDORED`, explicitly: git itself
   records that the path is another repository pinned at a commit.
2. a lockfile is `DERIVED_CACHE` -- explicitly when it carries its tool's
   `@generated` header, by *convention* only (an inferred candidate) when the
   evidence is its well-known name beside its manifest.
3. a self-declared generated header in the first lines of a non-template file is
   `GENERATED_PROJECTION`, explicitly, with the producer captured when the marker
   names one. Templates are excluded: a marker inside a template is text the
   template *emits*, not a statement about the template.
4. a generator declaration elsewhere in the same commit whose literal target path
   names this file (`declared_targets`) is `GENERATED_PROJECTION`, explicitly.
5. a self-declared "Hand-authored (not X-manufactured)" header is
   `CANONICAL_SOURCE`, explicitly. Not `HANDWRITTEN_IRREDUCIBLE`: hand authorship
   is declared; irreducibility is only ever the residue of a failed regeneration.
"""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass, field
from pathlib import Path, PurePosixPath
from typing import Any, Iterator, Mapping

from .corpus import RepositorySubject, git, verify_checkout
from .model import (
    ArtifactOrigin,
    EvidenceStrength,
    FactStanding,
    IECRefusal,
    Observation,
)

__all__ = [
    "tree_id",
    "CENSUS_EXTRACTOR",
    "CENSUS_VERSION",
    "Census",
    "FileRecord",
    "census",
    "iter_blobs",
    "read_blob",
]

CENSUS_EXTRACTOR = "autofde_lab.iec.crowns.census"
CENSUS_VERSION = "1"

_BINARY_PROBE = 8000  # the same window git uses to decide a blob is binary
_HEADER_LINES = 6

_LANGUAGES = {
    ".ex": "elixir",
    ".exs": "elixir",
    ".eex": "eex",
    ".heex": "heex",
    ".py": "python",
    ".rs": "rust",
    ".js": "javascript",
    ".mjs": "javascript",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".sh": "shell",
    ".md": "markdown",
    ".ttl": "turtle",
    ".rq": "sparql",
    ".json": "json",
    ".toml": "toml",
    ".yml": "yaml",
    ".yaml": "yaml",
    ".tla": "tla",
    ".tera": "tera",
    ".tmpl": "template",
    ".j2": "jinja",
    ".hbs": "handlebars",
    ".liquid": "liquid",
    ".lock": "lockfile",
}
_TEMPLATE_LANGUAGES = {
    "eex",
    "heex",
    "tera",
    "template",
    "jinja",
    "handlebars",
    "liquid",
}

# (lockfile, manifest it is resolved from, tool that writes it)
_LOCKFILES = {
    "mix.lock": ("mix.exs", "mix"),
    "Cargo.lock": ("Cargo.toml", "cargo"),
    "uv.lock": ("pyproject.toml", "uv"),
    "poetry.lock": ("pyproject.toml", "poetry"),
    "yarn.lock": ("package.json", "yarn"),
    "package-lock.json": ("package.json", "npm"),
    "pnpm-lock.yaml": ("package.json", "pnpm"),
    "Gemfile.lock": ("Gemfile", "bundler"),
}

# Self-declared generated headers. Each pattern must be a statement the producer
# wrote *about this file*; the named group `producer`, when present, is recorded.
_GENERATED_HEADERS = (
    re.compile(r"GENERATED by (?P<producer>\w[\w-]*)(?: from (?P<source>[^\s+,;]+))?"),
    re.compile(r"This file is automatically @generated by (?P<producer>\w[\w-]*)"),
    re.compile(r"Code generated by (?P<producer>[\w./-]+).*DO NOT EDIT"),
    re.compile(r"THIS IS AN AUTOGENERATED FILE\. DO NOT EDIT"),
)
# Self-declared hand authorship. The producer states that the file is *not* the
# output of a named generator, so its origin is canonical source -- explicitly.
# It does not make the file irreducible: only a failed regeneration can say that.
_HANDWRITTEN_HEADERS = (
    re.compile(r"Hand-authored \(not (?P<negated_producer>[\w-]+)-manufactured\)"),
)


@dataclass(frozen=True)
class FileRecord:
    path: str
    mode: str
    object_type: str
    object_id: str
    size: int
    binary: bool
    language: str | None
    origin: ArtifactOrigin
    origin_strength: EvidenceStrength
    origin_evidence: Mapping[str, Any] = field(default_factory=dict)

    def subject(self, repository_subject: RepositorySubject) -> str:
        return f"{repository_subject.uri}:{self.path}"

    def to_json(self) -> dict[str, Any]:
        return {
            "path": self.path,
            "mode": self.mode,
            "object_type": self.object_type,
            "object_id": self.object_id,
            "size": self.size,
            "binary": self.binary,
            "language": self.language,
            "origin": self.origin.value,
            "origin_strength": self.origin_strength.value,
            "origin_evidence": dict(self.origin_evidence),
        }


@dataclass(frozen=True)
class Census:
    subject: RepositorySubject
    files: tuple[FileRecord, ...]

    def file(self, path: str) -> FileRecord:
        for record in self.files:
            if record.path == path:
                return record
        raise IECRefusal("UNKNOWN_ORIGIN", f"{path} is not in {self.subject.uri}")

    def origin_counts(self) -> dict[str, int]:
        counts: dict[str, int] = {}
        for record in self.files:
            counts[record.origin.value] = counts.get(record.origin.value, 0) + 1
        return dict(sorted(counts.items()))

    def observations(self) -> list[Observation]:
        """Every census fact as a provenance-bearing observation."""
        out: list[Observation] = []
        for record in self.files:
            subject = record.subject(self.subject)
            for predicate, value in (
                ("iec:gitObjectId", record.object_id),
                ("iec:gitMode", record.mode),
                ("iec:sizeBytes", record.size),
                ("iec:binary", record.binary),
                ("iec:language", record.language),
            ):
                out.append(
                    Observation(
                        subject,
                        CENSUS_EXTRACTOR,
                        CENSUS_VERSION,
                        record.object_id,
                        predicate,
                        value,
                        FactStanding.OBSERVED,
                    )
                )
            origin_standing = {
                EvidenceStrength.EXPLICIT_DECLARATION: FactStanding.DERIVED_DETERMINISTIC,
                EvidenceStrength.CONVENTION: FactStanding.INFERRED_CANDIDATE,
                EvidenceStrength.NONE: FactStanding.UNKNOWN,
            }[record.origin_strength]
            out.append(
                Observation(
                    subject,
                    CENSUS_EXTRACTOR,
                    CENSUS_VERSION,
                    record.object_id,
                    "iec:artifactOrigin",
                    {
                        "origin": record.origin.value,
                        "evidence": dict(record.origin_evidence),
                    },
                    origin_standing,
                )
            )
        return out

    def to_json(self) -> dict[str, Any]:
        return {
            "schema": "autofde-lab.iec.census/1",
            "extractor": CENSUS_EXTRACTOR,
            "extractor_version": CENSUS_VERSION,
            "subject": self.subject.to_json(),
            "origin_counts": self.origin_counts(),
            "files": [record.to_json() for record in self.files],
        }


def _safe_path(raw: str) -> str:
    path = PurePosixPath(raw)
    if path.is_absolute() or ".." in path.parts or not raw:
        raise IECRefusal("REFUSED_PATH_ESCAPE", raw)
    return raw


def _ls_tree(checkout: Path, commit: str) -> list[tuple[str, str, str, str]]:
    raw = git(checkout, "ls-tree", "-r", "-z", "--full-tree", commit)
    entries = []
    for item in raw.split(b"\0"):
        if not item:
            continue
        meta, _, path = item.partition(b"\t")
        mode, object_type, object_id = meta.decode().split(" ")
        entries.append((mode, object_type, object_id, _safe_path(path.decode("utf-8"))))
    return entries


def iter_blobs(checkout: Path, object_ids: list[str]) -> Iterator[tuple[str, bytes]]:
    """Read many blobs in one `git cat-file --batch` round trip."""
    if not object_ids:
        return
    payload = "".join(f"{object_id}\n" for object_id in object_ids).encode()
    raw = git(checkout, "cat-file", "--batch", input_bytes=payload)
    offset = 0
    for _ in object_ids:
        header_end = raw.index(b"\n", offset)
        object_id, object_type, size = raw[offset:header_end].decode().split(" ")
        if object_type != "blob":
            raise IECRefusal(
                "BLOCKED_CORPUS_IDENTITY", f"{object_id} is a {object_type}"
            )
        start = header_end + 1
        end = start + int(size)
        yield object_id, raw[start:end]
        offset = end + 1


def read_blob(subject: RepositorySubject, checkout: Path, path: str) -> bytes:
    """The exact bytes of `path` at `subject.commit` (never the working tree)."""
    verify_checkout(subject, checkout)
    raw = git(
        Path(checkout), "cat-file", "blob", f"{subject.commit}:{_safe_path(path)}"
    )
    return raw


def _language(path: str) -> str | None:
    name = PurePosixPath(path).name
    if name in _LOCKFILES:
        return "lockfile"
    return _LANGUAGES.get(PurePosixPath(path).suffix.lower())


def _header_marker(
    content: bytes,
    patterns: tuple[re.Pattern[str], ...] = _GENERATED_HEADERS,
    rule: str = "",
) -> dict[str, str] | None:
    head = content[:4096].decode("utf-8", errors="replace").splitlines()[:_HEADER_LINES]
    for line in head:
        for pattern in patterns:
            match = pattern.search(line)
            if match:
                found = {
                    "rule": rule or "self-declared-generated-header",
                    "marker": line.strip(),
                }
                groups = {k: v.rstrip(".") for k, v in match.groupdict().items() if v}
                found.update(groups)
                return found
    return None


def census(
    subject: RepositorySubject,
    checkout: Path,
    *,
    declared_targets: Mapping[str, Mapping[str, str]] | None = None,
) -> Census:
    """Census every tree entry of `subject.commit`.

    `declared_targets` maps a repository path to the generator declaration that
    names it as a literal output (see `generators.declared_outputs`).
    """
    checkout = Path(checkout)
    verify_checkout(subject, checkout)
    entries = _ls_tree(checkout, subject.commit)
    paths = {path for _, _, _, path in entries}
    blob_ids = [
        object_id for _, object_type, object_id, _ in entries if object_type == "blob"
    ]
    contents = dict(iter_blobs(checkout, sorted(set(blob_ids))))
    declared_targets = declared_targets or {}

    records = []
    for mode, object_type, object_id, path in sorted(
        entries, key=lambda entry: entry[3]
    ):
        if object_type == "commit":
            records.append(
                FileRecord(
                    path,
                    mode,
                    object_type,
                    object_id,
                    0,
                    False,
                    None,
                    ArtifactOrigin.EXTERNAL_VENDORED,
                    EvidenceStrength.EXPLICIT_DECLARATION,
                    {"rule": "gitlink", "pinned_commit": object_id},
                )
            )
            continue
        if mode == "120000":
            raise IECRefusal("REFUSED_SYMLINK", f"{subject.uri}:{path}")
        content = contents[object_id]
        binary = b"\0" in content[:_BINARY_PROBE]
        language = _language(path)
        origin, strength, evidence = ArtifactOrigin.UNKNOWN, EvidenceStrength.NONE, {}
        marker = (
            None
            if binary or language in _TEMPLATE_LANGUAGES
            else _header_marker(content)
        )
        name = PurePosixPath(path).name
        lockfile = _LOCKFILES.get(name)
        sibling = str(PurePosixPath(path).with_name(lockfile[0])) if lockfile else ""
        if lockfile and (marker is not None or sibling in paths):
            # A lockfile is resolver output: a cache of the manifest's resolution,
            # not a projection of domain semantics. The marker, when present,
            # upgrades the evidence from naming convention to self-declaration.
            origin = ArtifactOrigin.DERIVED_CACHE
            strength = (
                EvidenceStrength.EXPLICIT_DECLARATION
                if marker is not None
                else EvidenceStrength.CONVENTION
            )
            evidence = {"rule": "lockfile", "manifest": sibling, "tool": lockfile[1]}
            if marker is not None:
                evidence["marker"] = marker["marker"]
        elif PurePosixPath(path).parent.name == "__pycache__" and path.endswith(".pyc"):
            # CPython's bytecode cache of a sibling module; the location is the
            # interpreter's own convention, not a statement inside the file.
            origin, strength = ArtifactOrigin.DERIVED_CACHE, EvidenceStrength.CONVENTION
            evidence = {"rule": "python-bytecode-cache", "tool": "cpython"}
        elif marker is not None:
            origin, strength, evidence = (
                ArtifactOrigin.GENERATED_PROJECTION,
                EvidenceStrength.EXPLICIT_DECLARATION,
                marker,
            )
        elif path in declared_targets:
            origin, strength = (
                ArtifactOrigin.GENERATED_PROJECTION,
                EvidenceStrength.EXPLICIT_DECLARATION,
            )
            evidence = {"rule": "declared-generator-target", **declared_targets[path]}
        elif not binary and (
            handwritten := _header_marker(
                content, _HANDWRITTEN_HEADERS, "self-declared-hand-authored"
            )
        ):
            origin, strength, evidence = (
                ArtifactOrigin.CANONICAL_SOURCE,
                EvidenceStrength.EXPLICIT_DECLARATION,
                handwritten,
            )
        if marker is not None and path in declared_targets:
            evidence = {**evidence, "declared_by": dict(declared_targets[path])}
        records.append(
            FileRecord(
                path,
                mode,
                object_type,
                object_id,
                len(content),
                binary,
                language,
                origin,
                strength,
                evidence,
            )
        )
    return Census(subject, tuple(records))


def tree_id(entries: list[tuple[str, str, str]]) -> str:
    """The git tree id of `(mode, object_id, path)` entries, computed without git.

    Lets a court ask "does replacing these files with regenerated bytes restore
    the frozen root tree?" without writing a single object into any repository.
    """
    root: dict[str, Any] = {}
    for mode, object_id, path in entries:
        node = root
        parts = path.split("/")
        for part in parts[:-1]:
            node = node.setdefault(part, {})
            if not isinstance(node, dict):
                raise IECRefusal(
                    "BLOCKED_CORPUS_IDENTITY", f"{path} collides with a file"
                )
        node[parts[-1]] = (mode, object_id)

    def build(node: dict[str, Any]) -> str:
        items = []
        for name, child in node.items():
            if isinstance(child, dict):
                items.append((name + "/", "40000", name, build(child)))
            else:
                items.append((name, child[0].lstrip("0") or "0", name, child[1]))
        items.sort(key=lambda item: item[0].encode("utf-8"))
        body = b"".join(
            f"{mode} {name}".encode("utf-8") + b"\0" + bytes.fromhex(object_id)
            for _, mode, name, object_id in items
        )
        return hashlib.sha1(b"tree %d\0" % len(body) + body).hexdigest()

    return build(root)
