"""IEC-C1: decompile, regenerate, and translation-validate one exact repository subject.

ARD section 25, step for step, against the committed generated outputs of one
frozen commit:

1. freeze the exact subject (`corpus.freeze_corpus`);
2. census it from the git object database (`census.census`);
3. classify origins, using the generators' own declarations (`generators`);
4. recover each output's kernel from its producer's ontology and gates, with an
   independent SPARQL engine (`kernel.pack_kernel`), and decompile the output
   into residue + kernel bindings (`decompile`);
5. prefer the existing generator; where it may not run here, say so as a typed
   `BLOCKED` court, not a silent substitution;
6. regenerate every subject into an isolated destination, from kernel + program
   only;
7. run the declared verifier sets against original and regenerated bytes;
8. preserve every mismatch as a counterexample;
9. refine a falsified hypothesis once, on new evidence, and record both courts;
10. emit translation-validation receipts, hypotheses, and promotion candidates.

Nothing here writes into the subject repository. The regenerated tree's identity
is checked by recomputing git tree ids in Python (`census.tree_id`).

Run from the command line:

    python -m autofde_lab.iec.crowns.crown --checkout ~/ggen_igniter --out receipts/v26.9.23/iec/c1
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path, PurePosixPath
from typing import Any, Mapping

from .antiunify import anti_unify, template_text, tokenize
from .census import Census, census, read_blob, tree_id
from .corpus import freeze_corpus, observe_checkout
from .court import (
    BLOB_IDENTITY,
    BYTE_IDENTITY,
    CourtReceipt,
    Verifier,
    VerifierResult,
    VerifierSet,
    git_blob_id,
    run_court,
)
from .decompile import (
    family_leave_one_out,
    find_bindings,
    flat_program,
    leave_one_out,
    row_program,
)
from .federation import GgenCreate
from .generators import DeclaredOutput, declared_outputs, declared_targets
from .kernel import PackKernel, pack_kernel
from .model import IECRefusal, Verdict, canonical_json, content_id
from .reflexion import analyze, normalized_containment, strip_whitespace_and_call_parens
from .templates import eex_chunks, literal_containment, split_frontmatter

__all__ = ["C1_REVISION", "run_c1"]

C1_REVISION = "v26.9.23-iec-c1"
HEADER_LINES = 4
FORMATTER_CALL = "Code.format_string!"


def _never(
    original: bytes, generated: bytes, context: Mapping[str, Any]
) -> VerifierResult:
    raise IECRefusal(
        "BLOCKED_EXECUTION_AUTHORITY", "this verifier only runs under a broker"
    )


NATIVE_VERIFIER_SET = VerifierSet(
    "ggen_igniter-native/1",
    (
        Verifier("mix-format-check-formatted", "1", "build", _never),
        Verifier("mix-compile-warnings-as-errors", "1", "build", _never),
        Verifier("mix-test", "1", "tests", _never),
    ),
)


def _template_literals(
    original: bytes, generated: bytes, context: Mapping[str, Any]
) -> VerifierResult:
    containment = literal_containment(context["chunks"], generated.decode("utf-8"))
    verdict = Verdict.PASS if containment.holds else Verdict.COUNTEREXAMPLE
    return VerifierResult(verdict, containment.detail, containment.to_json())


def _template_literals_modulo(
    original: bytes, generated: bytes, context: Mapping[str, Any]
) -> VerifierResult:
    containment = normalized_containment(
        context["chunks"], generated.decode("utf-8"), strip_whitespace_and_call_parens
    )
    verdict = Verdict.PASS if containment.holds else Verdict.COUNTEREXAMPLE
    return VerifierResult(
        verdict,
        containment.detail
        + " (after deleting whitespace and call parentheses on both sides)",
        containment.to_json(),
    )


def _row_heldout(
    original: bytes, generated: bytes, context: Mapping[str, Any]
) -> VerifierResult:
    results = context["heldout"]
    failed = [result for result in results if result["verdict"] != "PASS"]
    if failed:
        return VerifierResult(
            Verdict.COUNTEREXAMPLE,
            f"{len(failed)} of {len(results)} held-out rows not predicted from kernel facts",
            {"failed": failed},
        )
    return VerifierResult(
        Verdict.PASS,
        f"{len(results)} of {len(results)} rows predicted from a template learned without them",
    )


TEMPLATE_LITERALS = Verifier(
    "declared-template-mandatory-literals",
    "1",
    "generator-reflexion",
    _template_literals,
)
TEMPLATE_LITERALS_MODULO = Verifier(
    "declared-template-mandatory-literals-modulo-whitespace-and-call-parens",
    "1",
    "generator-reflexion",
    _template_literals_modulo,
)
ROW_HELDOUT = Verifier(
    "row-template-leave-one-out", "1", "generalization", _row_heldout
)


def _write_json(path: Path, value: Any) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False) + "\n"
    path.write_text(text, encoding="utf-8")
    return content_id(text)


def _slug(path: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "-", path).strip("-").lower()


def _producer_calls(
    census: Census, checkout: Path, needle: str
) -> list[dict[str, Any]]:
    """Every `lib/**/*.ex` line of the subject that contains `needle` (observed)."""
    hits = []
    for record in census.files:
        if not (record.path.startswith("lib/") and record.path.endswith(".ex")):
            continue
        text = read_blob(census.subject, checkout, record.path).decode(
            "utf-8", "replace"
        )
        for number, line in enumerate(text.splitlines(), start=1):
            if needle in line:
                hits.append({"path": record.path, "line": number, "text": line.strip()})
    return hits


def _kernel_path_coverage(
    kernel: PackKernel, census: Census, target: str
) -> list[dict[str, Any]]:
    """Siblings that match the kernel's own path pattern but are absent from it.

    For each kernel variable whose every value names a file beside the target, the
    values are anti-unified into a pattern; tree files in that directory matching
    the pattern but carried by no kernel row are candidates for an incomplete
    kernel. A candidate, never a verdict: the exclusion may be deliberate.
    """
    directory = PurePosixPath(target).parent
    paths = {record.path for record in census.files}
    found = []
    for binding, rows in kernel.rows.items():
        for var in sorted(set().union(*(row.keys() for row in rows))):
            values = [row.get(var, "") for row in rows]
            if len(values) < 2 or not all(
                str(directory / value) in paths for value in values
            ):
                continue
            generalization = anti_unify([tokenize(value) for value in values])
            shapes = {
                hole.index: _hole_shape(
                    [
                        generalization.binding_text(m, hole.index)
                        for m in range(len(values))
                    ]
                )
                for hole in generalization.holes
            }
            pattern = "^" + _pattern(generalization.template, shapes) + "$"
            siblings = sorted(
                path[len(str(directory)) + 1 :]
                for path in paths
                if PurePosixPath(path).parent == directory
            )
            uncovered = [
                name
                for name in siblings
                if re.match(pattern, name) and name not in values
            ]
            found.append(
                {
                    "binding": binding,
                    "variable": var,
                    "pattern": template_text(generalization.template),
                    "regex": pattern,
                    "directory": str(directory),
                    "kernel_members": len(values),
                    "uncovered_matches": uncovered,
                    "standing": "INFERRED_CANDIDATE"
                    if uncovered
                    else "DERIVED_DETERMINISTIC",
                    "falsifier": "the uncovered file is excluded on purpose (e.g. not yet accepted)",
                }
            )
    return found


_SHAPES = (
    (re.compile(r"^[a-z0-9]+$"), "[a-z0-9]+"),
    (re.compile(r"^[a-z0-9-]+$"), "[a-z0-9-]+"),
    (re.compile(r"^[A-Za-z0-9_.-]+$"), "[A-Za-z0-9_.-]+"),
)


def _hole_shape(bindings: list[str]) -> str:
    """The narrowest character class every observed binding of one hole fits."""
    if all(binding.isdigit() for binding in bindings):
        lengths = sorted({len(binding) for binding in bindings})
        return rf"\d{{{lengths[0]},{lengths[-1]}}}"
    for shape, regex in _SHAPES:
        if all(shape.match(binding) for binding in bindings):
            return regex
    return ".+?"


def _pattern(template: Any, shapes: Mapping[int, str]) -> str:
    from .antiunify import Hole

    if isinstance(template, str):
        return re.escape(template)
    if isinstance(template, Hole):
        return shapes[template.index]
    return "".join(_pattern(child, shapes) for child in template.children)


def _declared_sort_keys(chunks: list[Any]) -> list[str]:
    keys = []
    for chunk in chunks:
        if chunk.kind in ("output", "code"):
            keys.extend(
                re.findall(r"sort_by\([^,]+,\s*&\s*&1\[\"(\w+)\"\]\)", chunk.text)
            )
    return keys


def _interpolated_row_keys(chunks: list[Any]) -> set[str]:
    keys: set[str] = set()
    for chunk in chunks:
        if chunk.kind == "output":
            keys.update(re.findall(r"row\[\"(\w+)\"\]", chunk.text))
    return keys


def _run_subject(
    census: Census, checkout: Path, output: DeclaredOutput, destination: Path, out: Path
) -> dict[str, Any]:
    subject = census.subject
    record = census.file(output.target)
    kernel = pack_kernel(census, checkout, output.template)
    facts = kernel.facts()
    original = read_blob(subject, checkout, output.target)
    text = original.decode("utf-8")
    _header, _unsupported, body = split_frontmatter(kernel.template_text)
    chunks = eex_chunks(body)
    slug = _slug(output.target)
    subject_uri = f"{subject.uri}:{output.target}"
    hypotheses: list[dict[str, Any]] = []
    refusals: list[dict[str, str]] = []

    program: dict[str, Any]
    heldout: list[dict[str, Any]] | None = None
    multi = [(name, rows) for name, rows in kernel.rows.items() if len(rows) >= 2]
    regenerated_text: str | None = None
    if len(multi) == 1:
        name, rows = multi[0]
        try:
            rp = row_program(text, name, rows)
        except IECRefusal as refusal:
            # The output's shape is not one line per row: the row court cannot
            # judge it, so it is not in this subject's verifier set.
            refusals.append(
                {"code": refusal.code, "detail": refusal.detail, "stage": "row-program"}
            )
            rp = None
        if rp is not None:
            heldout = leave_one_out(text, name, rows)
            program = {"kind": "row", **rp.to_json()}
            try:
                regenerated_text = rp.regenerate(rows)
            except IECRefusal as refusal:
                # Lines pair to kernel rows, yet some hole equals no kernel value:
                # the kernel does not explain the output. That is a counterexample
                # for the row court, never a reason to fall back to a flat program.
                refusals.append(
                    {
                        "code": refusal.code,
                        "detail": refusal.detail,
                        "stage": "row-regenerate",
                    }
                )
                heldout.append(
                    {
                        "held_out_line": None,
                        "verdict": "COUNTEREXAMPLE",
                        "detail": refusal.detail,
                    }
                )
            declared = _declared_sort_keys(chunks)
            hypotheses.append(
                {
                    "id": f"{slug}:row-order",
                    "subject": subject_uri,
                    "question": f"which kernel variable orders the {name} rows",
                    "surviving": list(rp.order_hypotheses),
                    "declared_by_template": declared,
                    "reflexion": "CONVERGENT"
                    if declared and set(declared) <= set(rp.order_hypotheses)
                    else "DIVERGENT_OR_UNDECLARED",
                    "standing": "UNKNOWN"
                    if len(rp.order_hypotheses) > 1
                    else "DERIVED_DETERMINISTIC",
                    "falsifier": "a kernel whose rows sort differently under the surviving variables",
                }
            )
            interpolated = _interpolated_row_keys(chunks)
            for constant in rp.constant_literals:
                hypotheses.append(
                    {
                        "id": f"{slug}:constant:{constant['variable']}",
                        "subject": subject_uri,
                        "question": f"is {constant['variable']} a kernel variable or template text",
                        "observation": f"every row has {constant['variable']}={constant['value']!r}; "
                        "the recovered row template holds it as literal text",
                        "declared_by_template": "interpolated"
                        if constant["variable"] in interpolated
                        else "not interpolated",
                        "standing": "UNKNOWN",
                        "falsifier": f"one row whose {constant['variable']} differs from "
                        f"{constant['value']!r}",
                    }
                )
    if regenerated_text is None:
        fp = flat_program(text, facts)
        regenerated_text = fp.regenerate(facts)
    if heldout is None:
        program = {
            "kind": "flat",
            "coverage": fp.coverage(),
            "bindings": [binding.to_json() for binding in fp.bindings],
            "note": "a flat program reconstructs by construction; its evidential value "
            "is exact-subject binding and declared-template reflexion, not generalization",
        }

    target = destination / output.target
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(regenerated_text.encode("utf-8"))
    generated = target.read_bytes()

    context = {
        "expected_blob_id": record.object_id,
        "chunks": chunks,
        "heldout": heldout or [],
    }
    static_verifiers = [BYTE_IDENTITY, BLOB_IDENTITY, TEMPLATE_LITERALS]
    if heldout is not None:
        static_verifiers.append(ROW_HELDOUT)
    static = VerifierSet(
        "iec-c1-static-row/1" if heldout is not None else "iec-c1-static-flat/1",
        tuple(static_verifiers),
    )
    courts: list[CourtReceipt] = [
        run_court(
            subject_uri,
            original,
            generated,
            static,
            original_identity=record.object_id,
            generated_identity=git_blob_id(generated),
            context=context,
        )
    ]
    raw_result = dict(courts[0].results)[TEMPLATE_LITERALS.name]
    if raw_result.verdict is Verdict.COUNTEREXAMPLE:
        evidence = _producer_calls(census, checkout, FORMATTER_CALL)
        hypotheses.append(
            {
                "id": f"{slug}:producer-postprocessing",
                "subject": subject_uri,
                "question": "is the committed output the raw template render",
                "h_raw": "FALSIFIED by the declared-template-mandatory-literals counterexample",
                "h_formatter": f"committed = {FORMATTER_CALL}(render) -- differences limited "
                "to layout and call parentheses",
                "evidence": evidence,
                "standing": "INFERRED_CANDIDATE",
                "falsifier": "a template literal whose non-whitespace, non-parenthesis text "
                "is absent from the output",
            }
        )
        if evidence:
            refined = VerifierSet(
                static.name.replace("iec-c1-static", "iec-c1-static-modulo-formatter"),
                tuple(
                    TEMPLATE_LITERALS_MODULO if v is TEMPLATE_LITERALS else v
                    for v in static_verifiers
                ),
            )
            courts.append(
                run_court(
                    subject_uri,
                    original,
                    generated,
                    refined,
                    original_identity=record.object_id,
                    generated_identity=git_blob_id(generated),
                    context=context,
                )
            )
    native = run_court(
        subject_uri,
        original,
        generated,
        NATIVE_VERIFIER_SET,
        original_identity=record.object_id,
        generated_identity=git_blob_id(generated),
        blocked={
            verifier.name: "BLOCKED_EXECUTION_AUTHORITY: this session's execution policy refused "
            "running the subject's Mix build (`mix deps.get && mix compile`); ARD section 22 "
            "requires brokered execution for active probes"
            for verifier in NATIVE_VERIFIER_SET.verifiers
        },
    )
    courts.append(native)

    reflexion = analyze(chunks, text, facts)
    coverage = _kernel_path_coverage(kernel, census, output.target)
    kernel_digest = _write_json(
        out / "kernels" / f"{kernel.pack}.json", kernel.to_json()
    )
    program_digest = _write_json(out / "programs" / f"{slug}.json", program)
    reflexion_digest = _write_json(out / "reflexion" / f"{slug}.json", reflexion)
    court_digests = {}
    for court in courts:
        name = court.verifier_set.name.replace("/", "-")
        court_digests[court.verifier_set.name] = _write_json(
            out / "translation-validations" / f"{slug}.{name}.json", court.to_json()
        )
    return {
        "subject": subject_uri,
        "target": output.target,
        "template": output.template,
        "pack": kernel.pack,
        "kernel_id": kernel.id,
        "original_blob": record.object_id,
        "generated_blob": git_blob_id(generated),
        "regenerated_path": str(target),
        "program_kind": program["kind"],
        "courts": {
            court.verifier_set.name: {
                "verdict": court.verdict.value,
                "claim": court.claim,
                "receipt_id": court.receipt_id,
                "dimensions": court.dimensions,
            }
            for court in courts
        },
        "counterexamples": [
            item for court in courts for item in court.counterexamples()
        ],
        "hypotheses": hypotheses,
        "refusals": refusals,
        "kernel_path_coverage": coverage,
        "reflexion_counts": reflexion["finding_counts"],
        "restated_declarations": sorted(
            {
                finding["value"]
                for finding in reflexion["findings"]
                if finding["kind"] == "LITERAL_RESTATES_DECLARATION"
            }
        ),
        "computed_holes": [
            {
                "value": finding["value"],
                "template_expression": finding["template_expression"],
            }
            for finding in reflexion["findings"]
            if finding["kind"] == "COMPUTED_HOLE"
        ],
        "digests": {
            "kernel": kernel_digest,
            "program": program_digest,
            "reflexion": reflexion_digest,
            "courts": court_digests,
        },
        "_generated_bytes": generated,
        "_header_facts": {
            key: facts[key] for key in facts if key.startswith("declaration:")
        },
        "_text": text,
    }


def _header_family(runs: list[dict[str, Any]], census: Census) -> dict[str, Any]:
    members = [
        run
        for run in runs
        if census.file(run["target"]).origin_evidence.get("rule")
        == "self-declared-generated-header"
    ]
    if len(members) < 3:
        return {
            "verdict": "UNSUPPORTED",
            "detail": f"{len(members)} self-declared members (< 3)",
        }
    texts = [
        "".join(run["_text"].splitlines(keepends=True)[:HEADER_LINES])
        for run in members
    ]
    facts = [run["_header_facts"] for run in members]
    heldout = family_leave_one_out(texts, facts)
    whole = anti_unify(
        [
            tokenize(text, [(b.start, b.end) for b in find_bindings(text, fact)])
            for text, fact in zip(texts, facts)
        ]
    )
    return {
        "members": [run["target"] for run in members],
        "header_lines": HEADER_LINES,
        "template": template_text(whole.template),
        "compression": whole.compression(),
        "leave_one_out": heldout,
        "verdict": "PASS"
        if all(item["verdict"] == "PASS" for item in heldout)
        else "COUNTEREXAMPLE",
        "reading": "the generated header is a projection of each pack's declaration "
        "(pack name, `to:` target, ontology path), restated as literal text in every template",
    }


def _federate(
    ggen_create: Path,
    census: Census,
    checkout: Path,
    runs: list[dict[str, Any]],
    scratch: Path,
) -> dict[str, Any]:
    """Route what ggen-create can represent to ggen-create; keep its refusals."""
    federated = GgenCreate(ggen_create)
    roles = federated.role_classes(census, checkout)
    role_map = roles.pop("roles")
    roles["roles_digest"] = content_id(role_map)
    probe = federated.differential_probe(scratch)
    members = [
        run
        for run in runs
        if census.file(run["target"]).origin_evidence.get("rule")
        == "self-declared-generated-header"
    ]
    per_line = []
    for line in range(HEADER_LINES):
        texts = [run["_text"].splitlines(keepends=True)[line] for run in members]
        facts = [run["_header_facts"] for run in members]
        occurring = [
            key
            for key in (
                "declaration:pack.name",
                "declaration:template.to",
                "declaration:pack.ontology",
            )
            if all(fact[key] in text for fact, text in zip(facts, texts))
        ]
        attempts = []
        for keys in (["declaration:pack.name"], occurring):
            if not keys or any(attempt["seed_keys"] == keys for attempt in attempts):
                continue
            results = federated.family_heldout(texts, facts, keys)
            verdicts = sorted({result["verdict"] for result in results})
            attempts.append(
                {
                    "seed_keys": keys,
                    "verdict": verdicts[0] if len(verdicts) == 1 else "MIXED",
                    "refusals": sorted(
                        {
                            r["ggen_create_refusal"]
                            for r in results
                            if "ggen_create_refusal" in r
                        }
                    ),
                    "results": results,
                }
            )
        routed = next((a for a in attempts if a["verdict"] == "PASS"), None)
        per_line.append(
            {
                "line": line + 1,
                "facts_occurring": occurring,
                "attempts": attempts,
                "routed_to": "ggen-create" if routed else "iec-anti-unification",
                "capability_falsifier": None
                if routed
                else {
                    "pr": "PR-005",
                    "statement": "ggen-create cannot represent this line's hole as a seed",
                    "refusals": sorted(
                        {code for a in attempts for code in a["refusals"]}
                    ),
                },
            }
        )
    return {
        "schema": "autofde-lab.iec.federation.ggen-create/1",
        "producer": federated.identity(),
        "role_classes": roles,
        "differential_probe": probe,
        "header_family_members": [run["target"] for run in members],
        "header_family_by_line": per_line,
    }


def run_c1(
    checkout: Path,
    out: Path,
    destination: Path,
    *,
    repository: str = "seanchatmangpt/ggen_igniter",
    branch: str = "main",
    commit: str = "HEAD",
    ggen_create: Path | None = None,
    scratch: Path | None = None,
) -> dict[str, Any]:
    checkout, out, destination = Path(checkout), Path(out), Path(destination)
    subject = observe_checkout(
        checkout,
        repository=repository,
        branch=branch,
        visibility="public",
        inclusion_reason="IEC-C1: first regeneration crown (PRD/ARD v26.9.23 section 25)",
        commit=commit,
    )
    corpus = freeze_corpus([subject], revision=C1_REVISION)
    base = census(subject, checkout)
    outputs = declared_outputs(base, checkout)
    classified = census(subject, checkout, declared_targets=declared_targets(outputs))
    paths = {record.path for record in classified.files}
    committed = [
        o
        for o in outputs
        if o.literal and o.target in paths and o.syntax == "eex-frontmatter"
    ]
    if not committed:
        raise IECRefusal(
            "UNSUPPORTED_GENERATOR_CAPABILITY",
            f"{subject.uri} commits no declared output",
        )

    out.mkdir(parents=True, exist_ok=True)
    digests = {
        "corpus.json": _write_json(out / "corpus.json", corpus.to_json()),
        "census.json": _write_json(out / "census.json", classified.to_json()),
        "declared-outputs.json": _write_json(
            out / "declared-outputs.json",
            {
                "schema": "autofde-lab.iec.declared-outputs/1",
                "subject": subject.uri,
                "outputs": [
                    {**o.to_json(), "committed": o.literal and o.target in paths}
                    for o in outputs
                ],
            },
        ),
    }
    runs = [
        _run_subject(classified, checkout, output, destination, out)
        for output in committed
    ]

    replaced = {run["target"]: run["generated_blob"] for run in runs}
    entries = [
        (r.mode, replaced.get(r.path, r.object_id), r.path) for r in classified.files
    ]
    without = [
        (r.mode, r.object_id, r.path)
        for r in classified.files
        if r.path not in replaced
    ]
    regenerated_tree = tree_id(entries)
    tree_court = {
        "schema": "autofde-lab.iec.tree-identity/1",
        "subject": subject.uri,
        "frozen_tree": subject.tree,
        "tree_without_regenerated_subjects": tree_id(without),
        "tree_with_regenerated_subjects": regenerated_tree,
        "regenerated_paths": sorted(replaced),
        "verdict": Verdict.PASS.value
        if regenerated_tree == subject.tree
        else Verdict.COUNTEREXAMPLE.value,
        "reading": "delete the generated subjects, regenerate them from kernel + program, "
        "and the frozen root tree id is restored",
    }
    digests["tree-identity.json"] = _write_json(out / "tree-identity.json", tree_court)
    family = _header_family(runs, classified)
    digests["families/generated-header.json"] = _write_json(
        out / "families" / "generated-header.json", family
    )

    if ggen_create is not None:
        scratch_root = (
            Path(scratch)
            if scratch is not None
            else destination.parent / (destination.name + ".ggen-create")
        )
        scratch_root.mkdir(parents=True, exist_ok=True)
        federation = _federate(
            Path(ggen_create), classified, checkout, runs, scratch_root
        )
    else:
        federation = {
            "schema": "autofde-lab.iec.federation.ggen-create/1",
            "verdict": "BLOCKED",
            "detail": "BLOCKED_CORPUS_IDENTITY: no ggen-create checkout supplied (--ggen-create)",
        }
    digests["federation/ggen-create.json"] = _write_json(
        out / "federation" / "ggen-create.json", federation
    )

    counterexamples = [item for run in runs for item in run["counterexamples"]]
    probe = federation.get("differential_probe")
    if probe and probe["verdict"] == "COUNTEREXAMPLE":
        counterexamples.append(
            {
                "subject": f"git:{federation['producer']['repository']}@{federation['producer']['commit']}"
                ":src/ggen_create/cases.py#render_concrete_many",
                "verifier": "ggen-create-render-differential",
                "verdict": "COUNTEREXAMPLE",
                "detail": probe["contract"],
                "evidence": {
                    k: probe[k]
                    for k in (
                        "input",
                        "render_concrete",
                        "render_concrete_many",
                        "lifecycle",
                    )
                },
            }
        )
    hypotheses = [item for run in runs for item in run["hypotheses"]]
    for name, rows in (
        ("counterexamples.jsonl", counterexamples),
        ("hypotheses.jsonl", hypotheses),
    ):
        text = "".join(canonical_json(row) + "\n" for row in rows)
        (out / name).write_text(text, encoding="utf-8")
        digests[name] = content_id(text)

    promotion = _promotion_candidates(runs, family, subject.repository, federation)
    digests["promotion-plan.json"] = _write_json(out / "promotion-plan.json", promotion)

    subjects = []
    for run in runs:
        public = {key: value for key, value in run.items() if not key.startswith("_")}
        public.pop("regenerated_path")
        subjects.append(public)
    validated = [
        claim
        for run in runs
        for court in run["courts"].values()
        if (claim := court["claim"]) != "NOT_VALIDATED"
    ]
    receipt_body = {
        "schema": "autofde-lab.iec.c1-run-receipt/1",
        "revision": C1_REVISION,
        "corpus_id": corpus.id,
        "subject": subject.to_json(),
        "origin_counts": classified.origin_counts(),
        "declared_outputs": {
            "total": len(outputs),
            "literal": sum(1 for o in outputs if o.literal),
            "committed": len(committed),
        },
        "subjects": subjects,
        "tree_identity": tree_court["verdict"],
        "header_family": family.get("verdict"),
        "federation": {
            "producer": federation.get("producer"),
            "role_classes_joined": federation.get("role_classes", {}).get("joined"),
            "differential_probe": (federation.get("differential_probe") or {}).get(
                "verdict", "BLOCKED"
            ),
            "header_lines_routed": [
                line["routed_to"]
                for line in federation.get("header_family_by_line", [])
            ],
        },
        "validated_claims": validated,
        "native_verifier_set": NATIVE_VERIFIER_SET.to_json(),
        "claim_ceiling": "byte and exact-tree identity of regenerated subjects; mandatory-literal "
        "reflexion against the declared templates (static, never evaluated); held-out row and "
        "header prediction. NOT build, test, runtime, or formatter equivalence: the subject's "
        "native verifiers are BLOCKED in this run.",
        "files": digests,
    }
    receipt = {**receipt_body, "run_id": content_id(receipt_body)}
    _write_json(out / "run-receipt.json", receipt)
    return receipt


def _promotion_candidates(
    runs: list[dict[str, Any]],
    family: Mapping[str, Any],
    repository: str,
    federation: Mapping[str, Any],
) -> dict[str, Any]:
    candidates = [
        {
            "id": "PROMO-C1-01",
            "destination": repository,
            "kind": "verifier",
            "change": "add an in-sync court for committed generated outputs: re-render each "
            "declared literal `to:` target and compare bytes (the translation-validation "
            "receipts in this run are that court, executed statically)",
            "evidence": [run["subject"] for run in runs],
            "authority_required": "repository maintainer merge; no IEC authority",
        }
    ]
    restated = sorted({value for run in runs for value in run["restated_declarations"]})
    if restated:
        candidates.append(
            {
                "id": "PROMO-C1-02",
                "destination": repository,
                "kind": "template-change",
                "change": "interpolate the generated header (pack name, `--out` target, "
                "ontology path) from the template's own declaration instead of restating it "
                "as literal text",
                "evidence": {
                    "restated_values": restated,
                    "header_family": family.get("template"),
                },
                "authority_required": "repository maintainer merge; no IEC authority",
            }
        )
    uncovered = [
        {"subject": run["subject"], **item}
        for run in runs
        for item in run["kernel_path_coverage"]
        if item["uncovered_matches"]
    ]
    if uncovered:
        candidates.append(
            {
                "id": "PROMO-C1-03",
                "destination": repository,
                "kind": "kernel-completion",
                "change": "add the uncovered files to the kernel, or record why they are excluded",
                "evidence": uncovered,
                "authority_required": "repository maintainer merge; no IEC authority",
            }
        )
    probe = federation.get("differential_probe")
    if probe and probe["verdict"] == "COUNTEREXAMPLE":
        candidates.append(
            {
                "id": "PROMO-C1-04",
                "destination": federation["producer"]["repository"],
                "kind": "defect",
                "change": "cases.render_concrete_many drops the static text before every "
                "replacement; append text[cursor:replacement.start] before each replacement "
                "value, as cases.render_concrete does",
                "evidence": {
                    "exact_subject": federation["producer"],
                    "minimal": {
                        k: probe[k]
                        for k in ("input", "render_concrete", "render_concrete_many")
                    },
                    "user_visible": probe["lifecycle"],
                },
                "authority_required": "ggen-create maintainer merge; no IEC authority",
            }
        )
    return {"schema": "autofde-lab.iec.promotion-plan/1", "candidates": candidates}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--checkout", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    parser.add_argument("--destination", type=Path, help="isolated regeneration root")
    parser.add_argument("--repository", default="seanchatmangpt/ggen_igniter")
    parser.add_argument("--branch", default="main")
    parser.add_argument("--commit", default="HEAD")
    parser.add_argument(
        "--ggen-create", type=Path, help="pinned ggen-create checkout to federate"
    )
    parser.add_argument(
        "--scratch", type=Path, help="scratch root for federated lifecycle probes"
    )
    args = parser.parse_args(argv)
    destination = args.destination or (
        args.out.parent / (args.out.name + ".regenerated")
    )
    receipt = run_c1(
        args.checkout,
        args.out,
        destination,
        repository=args.repository,
        branch=args.branch,
        commit=args.commit,
        ggen_create=args.ggen_create,
        scratch=args.scratch,
    )
    summary = {
        "run_id": receipt["run_id"],
        "tree_identity": receipt["tree_identity"],
        "header_family": receipt["header_family"],
        "federation": receipt["federation"],
        "validated_claims": receipt["validated_claims"],
        "subjects": {
            s["target"]: {k: v["verdict"] for k, v in s["courts"].items()}
            for s in receipt["subjects"]
        },
    }
    print(json.dumps(summary, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    sys.exit(main())
