#!/usr/bin/env python3
"""Generic OCEL episode runner over any domain registered in
`autofde_lab.reasoning.domain_evidence_registry.DOMAIN_EVIDENCE_REGISTRY`
(GENERATED by ggen from `ontology/domain-evidence.ttl`).

Hand-written by design, not generated: this is domain-INVARIANT control
flow (materialize -> real Astar solve -> replay -> verify -> teardown ->
write real OCEL 2.0 JSON) that every registry entry drives identically. Per
this project's own maturity-matrix "Handler-gap size" dimension, putting
control flow here and only the per-domain FACTS in the ontology is the
correct split -- generating 19 near-duplicate scripts would inflate LOC
without adding real coverage; this one script plus a growing ontology does.

Every scikit-decide `DeterministicPlanningDomain` subclass (all of
`autofde_lab.hub.domain.*`) exposes the same real, uniform API this script
calls generically: `get_initial_state()`, `get_applicable_actions(state)`,
`get_next_state(state, action)`, `is_goal(state)` -- confirmed by reading
`terragoat_remediation.py` and `azuregoat_privesc.py` side by side before
writing this file. No per-domain bridge is required to drive a domain this
way; a `gymact_bridge.py` (where one exists) additionally gates real DO
actuation behind `Consequence`/authority, which this script does not attempt
-- it produces OCEL evidence for the domain's own planning/state-transition
correctness, not for gymact-actuated real-world consequence.

Usage:
    uv run python scripts/run_domain_gymact_ocel_episode.py --domain terragoat
"""

from __future__ import annotations

import argparse
import importlib
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from autofde_lab import utils
from autofde_lab.ocel.log import OcelLog
from autofde_lab.ocel.model import OcelAttribute, OcelAttributeValue, OcelObject
from autofde_lab.reasoning.domain_evidence_registry import DOMAIN_EVIDENCE_REGISTRY

REPO_ROOT = Path(__file__).parent.parent


def _attr(**kwargs: object) -> dict[str, OcelAttributeValue]:
    """Wrap plain Python values into typed `OcelAttributeValue`s -- the real
    log API requires this (`log.py:127`'s `_as_attributes` calls
    `OcelAttribute(k, v)` with `v` already typed; a raw str/int/bool fails
    `to_ocel2()`'s `attr.value.kind` lookup, confirmed by a real
    `AttributeError` this script hit before this helper was added)."""
    out: dict[str, OcelAttributeValue] = {}
    for k, v in kwargs.items():
        if isinstance(v, bool):
            out[k] = OcelAttributeValue.boolean(v)
        elif isinstance(v, int):
            out[k] = OcelAttributeValue.integer(v)
        elif isinstance(v, float):
            out[k] = OcelAttributeValue.floating(v)
        else:
            out[k] = OcelAttributeValue.string(str(v))
    return out


def run(domain_key: str) -> None:
    spec = DOMAIN_EVIDENCE_REGISTRY.get(domain_key)
    if spec is None:
        print(f"domain_evidence: no registry entry for {domain_key!r}; known: {sorted(DOMAIN_EVIDENCE_REGISTRY)}")
        raise SystemExit(1)

    module = importlib.import_module(spec.python_module_path)
    domain_cls = getattr(module, spec.domain_class_name)

    log = OcelLog.new()
    episode_obj = f"episode:{domain_key}"
    domain_obj = f"domain:{domain_key}"
    log = log.with_objects(
        OcelObject(episode_obj, "episode"),
        OcelObject(domain_obj, "domain", (OcelAttribute("domain_class", OcelAttributeValue.string(spec.domain_class_name)),)),
    )

    # materialize -- a real domain instance, real Astar solve.
    t0 = time.time_ns()
    domain = domain_cls()
    astar_cls = utils.load_registered_solver("Astar")
    plan: list[str] = []
    with astar_cls(domain_factory=lambda: domain) as solver:
        solver.solve()
        state = domain.get_initial_state()
        max_steps = 200
        for _ in range(max_steps):
            if domain.is_goal(state):
                break
            action = solver.sample_action(state)
            plan.append(action)
            state = domain.get_next_state(state, action)

    materialized_goal_reached = domain.is_goal(state)
    log = log.append_event(
        "ev:materialize", "materialize", [episode_obj, domain_obj],
        timestamp_ns=t0,
        attributes=_attr(standing="ALIVE" if materialized_goal_reached else "PARTIAL_ALIVE", plan_length=len(plan)),
    )

    if not materialized_goal_reached:
        print(f"domain_evidence[{domain_key}]: real Astar solve did not reach goal; partial plan={plan}")

    # act -- one OCEL event per real capability applied, in solved-plan order.
    for i, action_id in enumerate(plan):
        t = time.time_ns()
        log = log.append_event(
            f"ev:act:{i}", "act", [episode_obj, domain_obj],
            timestamp_ns=t,
            attributes=_attr(action_id=action_id, step_index=i),
        )

    final_state = state
    goal_reached = domain.is_goal(final_state)

    # verify -- fresh-instance-replay: a brand-new domain instance,
    # independent of `domain` above, replays the exact same recorded action
    # sequence and the terminal check is re-derived against IT, not the
    # acting instance's own object. This is the real verification-
    # independence mechanism from spec.verify_mode == "fresh-instance-replay".
    if spec.verify_mode == "fresh-instance-replay":
        fresh_domain = domain_cls()
        fresh_state = fresh_domain.get_initial_state()
        for action_id in plan:
            fresh_state = fresh_domain.get_next_state(fresh_state, action_id)
        verify_passed = fresh_domain.is_goal(fresh_state) and (fresh_state == final_state)
    else:
        raise NotImplementedError(
            f"verify_mode={spec.verify_mode!r} not yet implemented in this generic runner "
            "(only fresh-instance-replay is wired so far -- see "
            "docs/jira/2026-08-13-domain-maturity-l4/INDEX-AND-GGEN-DESIGN.md for the other 3 modes)"
        )

    log = log.append_event(
        "ev:verify", "verify", [episode_obj, domain_obj],
        timestamp_ns=time.time_ns(),
        attributes=_attr(standing="ALIVE" if verify_passed else "REFUSED", goal_reached=goal_reached, verify_mode=spec.verify_mode),
    )
    log = log.append_event(
        "ev:teardown", "teardown", [episode_obj, domain_obj],
        timestamp_ns=time.time_ns(),
        attributes=_attr(standing="ALIVE"),
    )

    validated = log.validate()
    document = validated.to_ocel2_json()

    out_path = REPO_ROOT / spec.evidence_out_path
    out_path.parent.mkdir(parents=True, exist_ok=True)
    import json
    out_path.write_text(json.dumps(document, indent=2, sort_keys=True))

    print(f"domain_evidence[{domain_key}]: plan_length={len(plan)} goal_reached={goal_reached} verify_passed={verify_passed}")
    print(f"domain_evidence[{domain_key}]: wrote {len(validated.events)} events to {out_path}")

    if not (goal_reached and verify_passed):
        raise SystemExit(1)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--domain", required=True, choices=sorted(DOMAIN_EVIDENCE_REGISTRY))
    args = parser.parse_args()
    run(args.domain)
