#!/usr/bin/env python3
"""Generic OCEL episode runner over any domain registered in
`autofde_lab.reasoning.domain_evidence_registry.DOMAIN_EVIDENCE_REGISTRY`
(GENERATED by ggen from `ontology/domain-evidence.ttl`).

Hand-written by design, not generated: this is domain-INVARIANT control
flow (materialize -> real Astar solve -> replay -> verify -> teardown ->
write real OCEL 2.0 JSON) that every registry entry drives identically. Per
this project's own maturity-matrix "Handler-gap size" dimension, putting
control flow here and only the per-domain FACTS in the ontology is the
correct split -- generating 19 near-duplicate scripts would inflate LOC
without adding real coverage; this one script plus a growing ontology does.

Every scikit-decide `DeterministicPlanningDomain` subclass (all of
`autofde_lab.hub.domain.*`) exposes the same real, uniform API this script
calls generically: `get_initial_state()`, `get_applicable_actions(state)`,
`get_next_state(state, action)`, `is_goal(state)` -- confirmed by reading
`terragoat_remediation.py` and `azuregoat_privesc.py` side by side before
writing this file. No per-domain bridge is required to drive a domain this
way; a `gymact_bridge.py` (where one exists) additionally gates real DO
actuation behind `Consequence`/authority, which this script does not attempt
-- it produces OCEL evidence for the domain's own planning/state-transition
correctness, not for gymact-actuated real-world consequence.

Usage:
    uv run python scripts/run_domain_gymact_ocel_episode.py --domain terragoat
"""

from __future__ import annotations

import argparse
import importlib
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from typing import Callable

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from autofde_lab import utils
from autofde_lab.ocel.log import OcelLog
from autofde_lab.ocel.model import OcelAttribute, OcelAttributeValue, OcelObject
from autofde_lab.reasoning.domain_evidence_registry import DOMAIN_EVIDENCE_REGISTRY

REPO_ROOT = Path(__file__).parent.parent

_PDDL_DIR = REPO_ROOT / "tests" / "domains" / "python" / "pddl_domains"
_BLOCKS_DOMAIN = str(_PDDL_DIR / "blocks" / "domain.pddl")
_BLOCKS_PROBLEM = str(_PDDL_DIR / "blocks" / "probBLOCKS-3-0.pddl")


def _build_fix_git() -> object:
    """Real temp git repo, same pattern as tests/domains/python/
    test_fix_git_domain.py's `fix_git_repo` fixture -- proven this session
    (uv run, real goal_reached=True, plan=[checkout_recovery, checkout_master,
    merge_recovery])."""
    from autofde_lab.hub.domain.fix_git import GitRecoveryDomain

    def _run_git(repo_dir: Path, *args: str) -> subprocess.CompletedProcess:
        return subprocess.run(["git", *args], cwd=repo_dir, check=True, capture_output=True, text=True)

    tmp_dir = Path(tempfile.mkdtemp(prefix="fix_git_domain_"))
    repo_dir = tmp_dir / "personal-site"
    repo_dir.mkdir()
    _run_git(repo_dir, "init", "-b", "master")
    _run_git(repo_dir, "config", "user.email", "domain-evidence@example.invalid")
    _run_git(repo_dir, "config", "user.name", "Domain Evidence Runner")
    (repo_dir / "_includes").mkdir()
    (repo_dir / "_layouts").mkdir()
    (repo_dir / "_includes" / "about.md").write_text("original about\n")
    (repo_dir / "_layouts" / "default.html").write_text("<html>original</html>\n")
    _run_git(repo_dir, "add", "-A")
    _run_git(repo_dir, "commit", "-m", "Initial site")
    _run_git(repo_dir, "checkout", "--detach", "HEAD")
    patch_dir = REPO_ROOT / "vendor" / "gyms" / "terminal-bench" / "fix-git" / "environment" / "resources" / "patch_files"
    (repo_dir / "_includes" / "about.md").write_text((patch_dir / "about.md").read_text())
    (repo_dir / "_layouts" / "default.html").write_text((patch_dir / "default.html").read_text())
    _run_git(repo_dir, "add", "-A")
    _run_git(repo_dir, "commit", "-m", "Move to Stanford")
    lost_commit = _run_git(repo_dir, "rev-parse", "HEAD").stdout.strip()
    _run_git(repo_dir, "checkout", "master")
    return GitRecoveryDomain(repo_dir=repo_dir, target_commit=lost_commit)


def _build_pddl() -> object:
    """Real BLOCKS_DOMAIN/BLOCKS_PROBLEM fixture files, same pattern as
    tests/domains/python/test_pddl_domain.py -- proven this session
    (goal_reached=True, plan_length=4)."""
    from autofde_lab.hub.domain.pddl import PDDLDomain

    return PDDLDomain(_BLOCKS_DOMAIN, _BLOCKS_PROBLEM)


def _build_plado() -> object:
    """Real blocksworld PDDL fixture via PladoPddlDomain (native encoding),
    same pattern as tests/domains/python/test_plado_domain.py's
    plado_native_domain_factory -- proven this session (goal_reached=True,
    plan_length=4). NOTE: the repo's own existing test
    (test_plado_domain_planning) calls solve()+rollout() but never asserts
    is_goal -- a real, pre-existing test gap this generic runner's episode
    now closes with a real goal-reaching check."""
    from autofde_lab.hub.domain.plado import ActionEncoding, PladoPddlDomain, StateEncoding

    return PladoPddlDomain(
        domain_path=_BLOCKS_DOMAIN,
        problem_path=_BLOCKS_PROBLEM,
        state_encoding=StateEncoding.NATIVE,
        action_encoding=ActionEncoding.NATIVE,
    )


def _build_up() -> object:
    """Real unified_planning Problem, same construction as tests/domains/
    python/test_up_bridge_domain.py's test_up_bridge_domain_planning --
    proven this session (goal_reached=True, plan_length=2, actions b then c,
    matching that test's own assertion)."""
    import unified_planning
    from unified_planning.shortcuts import Fluent, InstantaneousAction, Not

    from autofde_lab.hub.domain.up import UPDomain

    x = Fluent("x")
    y = Fluent("y")
    a = InstantaneousAction("a")
    a.add_precondition(Not(x))
    a.add_effect(x, True)
    b = InstantaneousAction("b")
    b.add_precondition(Not(y))
    b.add_effect(y, True)
    c = InstantaneousAction("c")
    c.add_precondition(y)
    c.add_effect(x, True)
    problem = unified_planning.model.Problem("simple_with_costs")
    problem.add_fluent(x)
    problem.add_fluent(y)
    problem.add_action(a)
    problem.add_action(b)
    problem.add_action(c)
    problem.set_initial_value(x, False)
    problem.set_initial_value(y, False)
    problem.add_goal(x)
    problem.add_quality_metric(unified_planning.model.metrics.MinimizeActionCosts({a: 10, b: 1, c: 1}))
    return UPDomain(problem, state_encoding="native")


def _build_chatman_clean_session() -> object:
    """Real TaskEnvelope + RouteSpec construction, same shape as this
    session's own ultracode grounding probe -- proven (goal_reached=True,
    plan_length=10, stage PARSE->...->STANDING, standing='ALIVE')."""
    from autofde_lab.hub.domain.chatman_clean_session import (
        ChatmanCleanSessionDomain,
        RouteOutcome,
        RouteSpec,
        TaskEnvelope,
    )

    return ChatmanCleanSessionDomain(
        TaskEnvelope(
            repo="seanchatmangpt/scikit-decide",
            base="0f32a25500262047539166a98facc29211e54d01",
            task="prove Clean-Session Environment Prime interoperability",
            acceptance="public domain API plus broker-bound execution and replay",
            constraints=("zero unreceipted actuation",),
            authority="repository owner",
        ),
        routes=(RouteSpec("exact_sha_sparse_tree", cost=1.0, outcome=RouteOutcome.SUCCESS),),
    )


# Named, per-domain exceptions to the default zero-arg `domain_cls()`
# construction -- real domains whose real __init__ needs arguments the
# ontology cannot itself supply (a temp git repo, PDDL file paths, a UP
# Problem object). Each factory here is real, tested code (see this
# session's ultracode grounding pass), not a stub.
_DOMAIN_FACTORIES: dict[str, Callable[[], object]] = {
    "fix_git": _build_fix_git,
    "pddl": _build_pddl,
    "plado": _build_plado,
    "up": _build_up,
    "chatman_clean_session": _build_chatman_clean_session,
}


def _attr(**kwargs: object) -> dict[str, OcelAttributeValue]:
    """Wrap plain Python values into typed `OcelAttributeValue`s -- the real
    log API requires this (`log.py:127`'s `_as_attributes` calls
    `OcelAttribute(k, v)` with `v` already typed; a raw str/int/bool fails
    `to_ocel2()`'s `attr.value.kind` lookup, confirmed by a real
    `AttributeError` this script hit before this helper was added)."""
    out: dict[str, OcelAttributeValue] = {}
    for k, v in kwargs.items():
        if isinstance(v, bool):
            out[k] = OcelAttributeValue.boolean(v)
        elif isinstance(v, int):
            out[k] = OcelAttributeValue.integer(v)
        elif isinstance(v, float):
            out[k] = OcelAttributeValue.floating(v)
        else:
            out[k] = OcelAttributeValue.string(str(v))
    return out


def run(domain_key: str) -> None:
    spec = DOMAIN_EVIDENCE_REGISTRY.get(domain_key)
    if spec is None:
        print(f"domain_evidence: no registry entry for {domain_key!r}; known: {sorted(DOMAIN_EVIDENCE_REGISTRY)}")
        raise SystemExit(1)

    module = importlib.import_module(spec.python_module_path)
    domain_cls = getattr(module, spec.domain_class_name)
    factory: Callable[[], object] = _DOMAIN_FACTORIES.get(domain_key, domain_cls)

    log = OcelLog.new()
    episode_obj = f"episode:{domain_key}"
    domain_obj = f"domain:{domain_key}"
    log = log.with_objects(
        OcelObject(episode_obj, "episode"),
        OcelObject(domain_obj, "domain", (OcelAttribute("domain_class", OcelAttributeValue.string(spec.domain_class_name)),)),
    )

    # materialize -- a real domain instance, real Astar solve.
    t0 = time.time_ns()
    domain = factory()
    astar_cls = utils.load_registered_solver("Astar")
    plan: list[str] = []
    with astar_cls(domain_factory=lambda: domain) as solver:
        solver.solve()
        state = domain.get_initial_state()
        max_steps = 200
        for _ in range(max_steps):
            if domain.is_goal(state):
                break
            action = solver.sample_action(state)
            plan.append(action)
            state = domain.get_next_state(state, action)

    materialized_goal_reached = domain.is_goal(state)
    log = log.append_event(
        "ev:materialize", "materialize", [episode_obj, domain_obj],
        timestamp_ns=t0,
        attributes=_attr(standing="ALIVE" if materialized_goal_reached else "PARTIAL_ALIVE", plan_length=len(plan)),
    )

    if not materialized_goal_reached:
        print(f"domain_evidence[{domain_key}]: real Astar solve did not reach goal; partial plan={plan}")

    # act -- one OCEL event per real capability applied, in solved-plan order.
    for i, action_id in enumerate(plan):
        t = time.time_ns()
        log = log.append_event(
            f"ev:act:{i}", "act", [episode_obj, domain_obj],
            timestamp_ns=t,
            attributes=_attr(action_id=action_id, step_index=i),
        )

    final_state = state
    goal_reached = domain.is_goal(final_state)

    # verify -- fresh-instance-replay: a brand-new domain instance,
    # independent of `domain` above, replays the exact same recorded action
    # sequence and the terminal check is re-derived against IT, not the
    # acting instance's own object. This is the real verification-
    # independence mechanism from spec.verify_mode == "fresh-instance-replay".
    if spec.verify_mode == "fresh-instance-replay":
        fresh_domain = factory()
        fresh_state = fresh_domain.get_initial_state()
        for action_id in plan:
            fresh_state = fresh_domain.get_next_state(fresh_state, action_id)
        verify_passed = fresh_domain.is_goal(fresh_state) and (fresh_state == final_state)
    else:
        raise NotImplementedError(
            f"verify_mode={spec.verify_mode!r} not yet implemented in this generic runner "
            "(only fresh-instance-replay is wired so far -- see "
            "docs/jira/2026-08-13-domain-maturity-l4/INDEX-AND-GGEN-DESIGN.md for the other 3 modes)"
        )

    log = log.append_event(
        "ev:verify", "verify", [episode_obj, domain_obj],
        timestamp_ns=time.time_ns(),
        attributes=_attr(standing="ALIVE" if verify_passed else "REFUSED", goal_reached=goal_reached, verify_mode=spec.verify_mode),
    )
    log = log.append_event(
        "ev:teardown", "teardown", [episode_obj, domain_obj],
        timestamp_ns=time.time_ns(),
        attributes=_attr(standing="ALIVE"),
    )

    validated = log.validate()
    document = validated.to_ocel2_json()

    out_path = REPO_ROOT / spec.evidence_out_path
    out_path.parent.mkdir(parents=True, exist_ok=True)
    import json
    out_path.write_text(json.dumps(document, indent=2, sort_keys=True))

    print(f"domain_evidence[{domain_key}]: plan_length={len(plan)} goal_reached={goal_reached} verify_passed={verify_passed}")
    print(f"domain_evidence[{domain_key}]: wrote {len(validated.events)} events to {out_path}")

    if not (goal_reached and verify_passed):
        raise SystemExit(1)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--domain", required=True, choices=sorted(DOMAIN_EVIDENCE_REGISTRY))
    args = parser.parse_args()
    run(args.domain)
