"""Passive provenance-bearing repository observation extraction."""

from __future__ import annotations

import hashlib
import posixpath
from dataclasses import dataclass
from pathlib import PurePosixPath
from typing import Iterable

from .model import (
    ArtifactClass,
    ArtifactRecord,
    EvidenceKind,
    Observation,
    Provenance,
    RepositorySubject,
    digest,
)

_GENERATED_MARKERS = (
    "generated by",
    "do not hand-edit",
    "do not edit",
    "@generated",
    "code generated",
)
_CANONICAL_NAMES = {
    "ontology.ttl",
    "ggen.toml",
    "pack.toml",
    "pyproject.toml",
    "cargo.toml",
    "package.json",
    "mix.exs",
}
_VENDOR_PREFIXES = ("vendor/", "third_party/", "third-party/", "deps/")
_CACHE_PARTS = {"__pycache__", ".cache", "target", "_build", "node_modules"}


@dataclass(frozen=True, slots=True)
class PassiveFile:
    path: str
    content: bytes
    executable: bool = False

    @property
    def content_digest(self) -> str:
        return "sha256:" + hashlib.sha256(self.content).hexdigest()


class ObservationExtractor:
    """Extract deterministic facts without executing observed repository code."""

    extractor_id = "iec.passive-file"
    extractor_version = "1"

    @staticmethod
    def normalize_path(path: str) -> str:
        candidate = path.replace("\\", "/")
        normalized = posixpath.normpath(candidate)
        if (
            normalized.startswith("../")
            or normalized == ".."
            or normalized.startswith("/")
        ):
            raise PermissionError(f"REFUSED_PATH_ESCAPE:{path}")
        if normalized in {".", ""}:
            raise ValueError("file path must identify a file")
        return normalized

    @staticmethod
    def _infer_producer(sample: str) -> str | None:
        for producer in ("ggen", "ggen_igniter", "protoc", "openapi", "graphql"):
            if producer.replace("_", " ") in sample or producer in sample:
                return producer
        return None

    @staticmethod
    def classify(
        path: str, content: bytes
    ) -> tuple[ArtifactClass, str | None, str | None]:
        normalized = ObservationExtractor.normalize_path(path)
        lower_path = normalized.lower()
        parts = set(PurePosixPath(lower_path).parts)

        if lower_path.startswith(_VENDOR_PREFIXES):
            return ArtifactClass.EXTERNAL_VENDORED, None, None
        if parts & _CACHE_PARTS:
            return ArtifactClass.DERIVED_CACHE, None, None

        sample = content[:16384].decode("utf-8", errors="ignore").lower()
        if any(marker in sample for marker in _GENERATED_MARKERS):
            producer = ObservationExtractor._infer_producer(sample)
            if producer is None:
                return (
                    ArtifactClass.UNKNOWN,
                    None,
                    "generated marker observed but producer identity is unknown",
                )
            return ArtifactClass.GENERATED_PROJECTION, producer, None

        basename = PurePosixPath(lower_path).name
        if basename in _CANONICAL_NAMES:
            return ArtifactClass.CANONICAL_SOURCE, None, None
        if lower_path.startswith(("ontology/", "queries/", "templates/")):
            return ArtifactClass.CANONICAL_SOURCE, None, None
        if lower_path.startswith(("archive/", "docs/archive/")):
            return ArtifactClass.HISTORICAL_RESIDUE, None, None

        return (
            ArtifactClass.UNKNOWN,
            None,
            "no deterministic producer/source rule matched",
        )

    def extract_file(
        self, subject: RepositorySubject, file: PassiveFile
    ) -> tuple[ArtifactRecord, tuple[Observation, ...]]:
        path = self.normalize_path(file.path)
        artifact_class, producer, unknown_reason = self.classify(path, file.content)
        provenance = Provenance(
            subject_id=subject.subject_id,
            path=path,
            extractor=self.extractor_id,
            extractor_version=self.extractor_version,
            source_digest=file.content_digest,
        )
        record = ArtifactRecord(
            subject_id=subject.subject_id,
            path=path,
            artifact_class=artifact_class,
            content_digest=file.content_digest,
            producer=producer,
            unknown_reason=unknown_reason,
        )
        suffix = PurePosixPath(path).suffix.lower()
        observations = (
            Observation("iec:path", path, provenance),
            Observation("iec:contentDigest", file.content_digest, provenance),
            Observation(
                "iec:artifactClass",
                artifact_class.value,
                provenance,
                EvidenceKind.DERIVED_DETERMINISTIC,
            ),
            Observation(
                "iec:fileSuffix",
                suffix,
                provenance,
                EvidenceKind.DERIVED_DETERMINISTIC,
            ),
            Observation("iec:executable", file.executable, provenance),
        )
        return record, observations

    def extract_repository(
        self, subject: RepositorySubject, files: Iterable[PassiveFile]
    ) -> tuple[tuple[ArtifactRecord, ...], tuple[Observation, ...]]:
        records: list[ArtifactRecord] = []
        observations: list[Observation] = []
        seen: set[str] = set()
        for file in sorted(files, key=lambda item: self.normalize_path(item.path)):
            normalized = self.normalize_path(file.path)
            if normalized in seen:
                raise ValueError(f"duplicate file observation: {normalized}")
            seen.add(normalized)
            record, facts = self.extract_file(subject, file)
            records.append(record)
            observations.extend(facts)
        return tuple(records), tuple(observations)


def observation_set_digest(observations: Iterable[Observation]) -> str:
    return digest(sorted(o.observation_id for o in observations))
