"""otel_equivalence_check.py — semantic (not byte) equivalence between the
direct `OcelLog` writer path's OCEL v2 JSON and the OTel-court path's
(ocel_accumulator's `/compact`) OCEL v2 JSON, for the SAME seed.

Invocation:
    python -m autofde_lab.sa2a.case_studies.manufacturing.otel_equivalence_check \
        <direct_path_ocel.json> <otel_path_ocel.json>

Checks (semantic, per MFG-01A.1 task spec):
  1. Same set of (resource_id, round_index) observation tuples.
  2. Same set of (resource_id, round_index) proposal tuples.
  3. Same set of (resource_id, round_index) actuation tuples.
  4. Same set of admitted-verdict (resource_id, round_index) tuples.
  5. Same total actuation count and same total receipt count.
  6. Same zero-unreceipted-actuation result (every actuation has a linked
     receipt object in both documents).
  7. Same zero-authority-violation result (no actuation applied without an
     admitted verdict, in both documents).
  8. Same max-round-energy result (max granted_energy_kwh over all
     odrl:Permission events, per document).

`round_index` is not carried as a native OCEL attribute by either path
today; this script recovers it from event/object id naming convention
(`<resource_id>-r<round_index>-...`), which both the direct-path
`runtime.py` (via ocel_adapter's event ids) and the OTel-court span
attributes (per telemetry.py's docstring contract) are documented to use.
If an id does not match that convention, this script raises rather than
silently skipping it — a naming-convention mismatch is a real defect to
surface, not one to paper over.
"""

from __future__ import annotations

import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

_ID_RE = re.compile(r"(?P<resource_id>[A-Za-z]+\d+)-r(?P<round_index>\d+)")


def _resource_round(object_or_event_id: str) -> tuple[str, int]:
    """Recover (resource_id, round_index) from an id such as ``M1-r0``,
    ``M3-r14-prop``, ``obs-M1-r0``, or ``evt-actuation-M3-r14-prop`` — the
    `<resource_id>-r<round_index>` substring may appear anywhere in the id,
    not only at its start, since different builders prefix/suffix it
    differently (see the real ids observed in both OCEL documents)."""
    m = _ID_RE.search(object_or_event_id)
    if not m:
        raise ValueError(
            f"id {object_or_event_id!r} does not match the "
            "<resource_id>-r<round_index>[-...] naming convention this "
            "script relies on to recover round_index"
        )
    return m.group("resource_id"), int(m.group("round_index"))


@dataclass
class OcelSummary:
    path: str
    observation_tuples: set = field(default_factory=set)
    proposal_tuples: set = field(default_factory=set)
    actuation_tuples: set = field(default_factory=set)
    admitted_tuples: set = field(default_factory=set)
    total_actuations: int = 0
    total_receipts: int = 0
    unreceipted_actuations: int = 0
    unauthorized_actuations: int = 0
    max_granted_energy_kwh: float = 0.0


def _attr_value(attrs: dict, name: str):
    """OCEL 2.0 JSON event/object attribute lookup: `attrs` is the event's
    `"attributes"` list of `{"name": ..., "value": ...}` dicts."""
    for a in attrs:
        if a.get("name") == name:
            return a.get("value")
    return None


def summarize(ocel_json_path: str) -> OcelSummary:
    doc = json.loads(Path(ocel_json_path).read_text())
    events = doc["events"]
    objects = {o["id"]: o for o in doc["objects"]}

    s = OcelSummary(path=ocel_json_path)

    # Map: proposal object id -> whether a receipt object was generated by
    # some actuation event that also `prov:used` that same proposal.
    actuation_events = [e for e in events if e["type"] == "sosa:Actuation"]
    permission_events = [e for e in events if e["type"] == "odrl:Permission"]
    prohibition_events = [e for e in events if e["type"] == "odrl:Prohibition"]
    observation_events = [e for e in events if e["type"] == "sosa:Observation"]

    for e in observation_events:
        # The equipment object id (e.g. "M1") carries no round_index -- the
        # observation event's OWN id (e.g. "obs-M1-r0") does.
        rid, rnd = _resource_round(e["id"])
        s.observation_tuples.add((rid, rnd))
        for rel in e.get("relationships", []):
            if rel.get("qualifier") == "prov:generated":
                # generated a Plan -> this is a proposal round for this resource
                plan_id = rel["objectId"]
                rid, rnd = _resource_round(plan_id)
                s.proposal_tuples.add((rid, rnd))

    admitted_proposal_ids: set[str] = set()
    round_energy_kwh: dict[int, float] = {}
    for e in permission_events:
        verdict = _attr_value(e.get("attributes", []), "verdict")
        granted = _attr_value(e.get("attributes", []), "granted_energy_kwh")
        proposal_id = None
        resource_id = None
        for rel in e.get("relationships", []):
            if rel.get("qualifier") == "prov:used":
                proposal_id = rel["objectId"]
            if rel.get("qualifier") == "odrl:assignee":
                resource_id = rel["objectId"]
        if (
            verdict == "admitted"
            and proposal_id is not None
            and resource_id is not None
        ):
            admitted_proposal_ids.add(proposal_id)
            rid, rnd = _resource_round(proposal_id)
            s.admitted_tuples.add((rid, rnd))
            if granted is not None:
                round_energy_kwh[rnd] = round_energy_kwh.get(rnd, 0.0) + float(granted)
    # "max-round-energy": max, over all rounds, of the TOTAL admitted
    # granted_energy_kwh across every resource that round -- not the max of
    # any single per-resource permission event (the otel-court's "authorize"
    # span attaches exactly this per-round total, per the real span attribute
    # observed live: `granted_energy_kwh: Double(222.5)` on a 4-resource
    # round -- the sum, not one resource's individual grant).
    s.max_granted_energy_kwh = (
        max(round_energy_kwh.values()) if round_energy_kwh else 0.0
    )

    receipted_actuation_count = 0
    for e in actuation_events:
        s.total_actuations += 1
        proposal_id = None
        receipt_id = None
        resource_id = None
        for rel in e.get("relationships", []):
            if rel.get("qualifier") == "prov:used":
                proposal_id = rel["objectId"]
            if rel.get("qualifier") == "prov:generated":
                receipt_id = rel["objectId"]
            if rel.get("qualifier") == "sosa:actsOnProperty":
                resource_id = rel["objectId"]
        if proposal_id is not None:
            rid, rnd = _resource_round(proposal_id)
            s.actuation_tuples.add((rid, rnd))
        if receipt_id is not None and receipt_id in objects:
            receipted_actuation_count += 1
        else:
            s.unreceipted_actuations += 1
        applied = _attr_value(e.get("attributes", []), "applied")
        if (
            applied
            and proposal_id is not None
            and proposal_id not in admitted_proposal_ids
        ):
            s.unauthorized_actuations += 1

    s.total_receipts = receipted_actuation_count
    return s


def compare(direct_path: str, otel_path: str) -> dict:
    d = summarize(direct_path)
    o = summarize(otel_path)

    checks = {
        "observation_tuples_equal": d.observation_tuples == o.observation_tuples,
        "proposal_tuples_equal": d.proposal_tuples == o.proposal_tuples,
        "actuation_tuples_equal": d.actuation_tuples == o.actuation_tuples,
        "admitted_tuples_equal": d.admitted_tuples == o.admitted_tuples,
        "total_actuations_equal": d.total_actuations == o.total_actuations,
        "total_receipts_equal": d.total_receipts == o.total_receipts,
        "zero_unreceipted_actuations_both": (
            d.unreceipted_actuations == 0 and o.unreceipted_actuations == 0
        ),
        "zero_authority_violations_both": (
            d.unauthorized_actuations == 0 and o.unauthorized_actuations == 0
        ),
        "max_granted_energy_kwh_equal": abs(
            d.max_granted_energy_kwh - o.max_granted_energy_kwh
        )
        < 1e-9,
    }
    return {
        "direct": d,
        "otel": o,
        "checks": checks,
        "semantically_equivalent": all(checks.values()),
    }


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(
            "usage: otel_equivalence_check.py <direct_path_ocel.json> <otel_path_ocel.json>",
            file=sys.stderr,
        )
        return 2
    direct_path, otel_path = argv[1], argv[2]
    for p, label in ((direct_path, "direct-path"), (otel_path, "otel-path")):
        if not Path(p).exists():
            print(
                f"BLOCKED:MISSING_INPUT — {label} OCEL JSON does not exist at {p!r}",
                file=sys.stderr,
            )
            return 3
    result = compare(direct_path, otel_path)
    d, o = result["direct"], result["otel"]
    print(f"direct path : {d.path}")
    print(
        f"  actuations={d.total_actuations} receipts={d.total_receipts} "
        f"unreceipted={d.unreceipted_actuations} unauthorized={d.unauthorized_actuations} "
        f"max_granted_energy_kwh={d.max_granted_energy_kwh}"
    )
    print(f"otel path   : {o.path}")
    print(
        f"  actuations={o.total_actuations} receipts={o.total_receipts} "
        f"unreceipted={o.unreceipted_actuations} unauthorized={o.unauthorized_actuations} "
        f"max_granted_energy_kwh={o.max_granted_energy_kwh}"
    )
    print("checks:")
    for name, ok in result["checks"].items():
        print(f"  {name}: {'PASS' if ok else 'FAIL'}")
    print(f"semantically_equivalent: {result['semantically_equivalent']}")
    return 0 if result["semantically_equivalent"] else 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
